### ISSUE TITLE
Does Libation work with other audiobook sources or just Audible and Local files?

### ISSUE THREAD

**Issue by LadyHaywood** [rmcrackan/Libation#1021]
I wanted to try out Libation but I can't find out if I can import my google play books audiobooks in the same way it does with audible. The only "yes" I can find it google's stupid ai search but I'm 100% sure it's wrong on this. I never look at it but last resort, I guess.

**Comment by wtanksleyjr** [comment]
If it helps, you can just download Google Play audiobooks ready to play -
go to your audiobook library on the website for Google Play, click the
"..." menu on a book cover you own, and click "Export". It'll ask you what
quality you want, and there you go, an MP4 file ready to play on any
software that supports MP4s.

What you want is book player software, which Libation isn't. I use
Audiobookshelf because my main book player is my phone.

-Wm

**Comment by LadyHaywood** [comment]
> you can just download Google Play audiobooks ready to play

Sadly, not all audiobooks are able to be downloaded. My "audiobooks" fall into the radio show/full cast/(un)abridged types and they aren't expotable.

**Comment by wtanksleyjr** [comment]
Oof, thanks, I didn't know they DID that, so good to know (yikes). Anyhow,
yeah, Libation has a TON of effort put into it just to work with Audible,
working with Google too would depend on someone figuring out Google's
protection first.

-Wm

**Comment by rmcrackan** [comment]
Yeah, it's all about what it's worth it to solve. Audible is essentially a monopoly -- it's 2/3 of the entire audiobook market. If that final 1/3 were a single company then it *might* be a nut worth trying to crack. In reality, it's extremely fractured and even the largest players are a distant second place. Google Play Books is only 5%
