### ISSUE TITLE
I can't import library.

### ISSUE THREAD

**Issue by TheBookishDad** [rmcrackan/Libation#1038]
**Describe the bug**
nothing happens when i log in

**To Reproduce**

1. I click import and try logging in and after nothing happens
2. I've tried the amazon login pop up and the advanced way by copying the url code and doing that way.
3. I also tried a pre release i saw in another issue post. Also deleted the account settin json file and restarted the process.
4. See error here's my log
[_Log202411_001.zip](https://github.com/user-attachments/files/17718503/_Log202411_001.zip)

**Platform**
Windows 11 home

**Log Files**
see number 4.

**Comment by TheBookishDad** [comment]
it was working fine last month. then i added a few recently so i opened libation today and couldn't log in for an unknown reason. i try to login and one i go through the steps its like ive logged in but no new audios will be imported.

**Comment by rmcrackan** [comment]
I'm at a loss. Those steps you said at the top are exactly what should fix it.

* Some bugs are fixed in more recent pre releases.
* That more complex url-copy login method should work 100% of the time because it's literally logging into amazon with your own browser.
* Deleting/renaming the AccountSettings.json will forget any past logins and make you log in again.

I'm only mentioning these obvious points since I'm out of ideas: are you sure you selected the correct region/locale in the account's dropdown? Are you sure the email/username is correct and free of typos? Is the result different if you're on a different wifi network (friend's house, coffee shop, work, phone hot-spot, ...?)

**Comment by TheBookishDad** [comment]
well shoot lol i disabled my vpn and it worked lmao...
