### ISSUE TITLE
App crashes since this past week.  

### ISSUE THREAD

**Issue by Willows227** [rmcrackan/Libation#1053]
**Describe the bug**
I have been using Libation quite successfully for a few months now.  Over this past week, the app began downloading only 4-6 books before it would freeze up and I would have to manually close it and reboot my computer to open it again.  Then yesterday it completely crashed and won't even open after a reboot. I tried deleting and reinstalling (nope) and reinstalling onto a different drive (nope).

I finally installed the Classic Windows version and with that installation I finally got it to report an "unexpected error" to me.

Thanks for checking this out for me!  I love this app and all you have done to make it happen for others.
Willows227

**Expected behavior**
For it to run as usual. :)

**Platform**

Windows 10

**Log Files**
Attach your Libation log file here.
[_Log202411_014.zip](https://github.com/user-attachments/files/17846443/_Log202411_014.zip)

**Comment by rmcrackan** [comment]
Thank you very much for your log file. I'm so sorry about this. It's a bug which is fixed in recent pre-releases but I'm about to leave town for a while and I know better than to do a release and then be absent.

In rare circumstances, it's possible for `AccountsSettings.json` file to get corrupted. It's in the same folder as the log file. Delete this, restart Libation, and go into Settings > Accounts to re-add your account info. You'll also have to log in again. Fortunately no other info or files are affected by this bug.

**Comment by Willows227** [comment]
It worked!  Thank you so much for the speedy and helpful response!  I hope you have a restful time out of town.

Thanks
Willows227

**Comment by rmcrackan** [comment]
Thanks! We're very much looking forward to the vacation.
