### ISSUE TITLE
Libation won't launch

### ISSUE THREAD

**Issue by yaboidillon** [rmcrackan/Libation#1061]
**Describe the bug**
Libation has been not launching for me for a few months now. I am not sure why.

**To Reproduce**

1. Go to Libation shortcut on desktop, or, C:\Users\Dillon\Libation
2. Click to launch program
3. Try running as administrator
4. Persistently, nothing happens.

**Expected behavior**
The program used to launch successfully.

**Platform**

Windows 10

**Comment by rmcrackan** [comment]
Sorry about this. Can you attach your log file to this ticket?

**Comment by yaboidillon** [comment]
> Sorry about this. Can you attach your log file to this ticket?

I am not sure how.

**Comment by rmcrackan** [comment]
Inside `C:\Users\Dillon\Libation`, are there any files which look similar to "Log202412.zip"? Please attach the latest one of these to this ticket. You can drag and drop the file into the area where you type your reply on github.

**Comment by yaboidillon** [comment]
[_Log202311.zip](https://github.com/user-attachments/files/17972448/_Log202311.zip)
[_Log202311_001.zip](https://github.com/user-attachments/files/17972450/_Log202311_001.zip)

[_Log202312.zip](https://github.com/user-attachments/files/17972451/_Log202312.zip)


Here's all the recent ones.

**Comment by rmcrackan** [comment]
Thanks. These are from a year ago. What happens if you download, unzip, and run the latest version?

https://github.com/rmcrackan/Libation/releases/tag/v11.1.0

**Comment by yaboidillon** [comment]
I downloaded the latest version (I clicked Windows 11.1.0 Chardonnay, not sure what the difference is between classic and chardonnay), and replaced all files with the new files, and when I click the desktop shortcut, still nothing happens.

However, there does not appear to be a new log file either. The most recent one is from Dec. 1st. But I am attempting to run the program (today, on Dec. 2nd), and run as administrator.

**Comment by rmcrackan** [comment]
For nothing at all to happen is odd. Maybe anti-virus is blocking it?

**Comment by yaboidillon** [comment]
Well, I do have Steam. I have had Steam install DRM software without my knowledge or consent in the past. But that was to do with torrents.

I don't have any antivirus besides stock Windows 10 stuff.

**Comment by rmcrackan** [comment]
Possible but unlikely. Since you have windows 10, maybe this can help: open the folder where Libation is. In that address bar, type `cmd` and hit Enter. In the new command window type `Libation` and hit Enter. Maybe we'll get lucky and it will display some error in the command window that the graphic interface otherwise hides when it fails.

![Screenshot 2024-12-02 22 56 22](https://github.com/user-attachments/assets/4106d9af-cc34-4cf4-8747-8d765b714774)

![Screenshot 2024-12-02 22 56 29](https://github.com/user-attachments/assets/239b98a4-7a39-4b37-b659-aa1c6b28c447)

![Screenshot 2024-12-02 22 56 36](https://github.com/user-attachments/assets/5c5e78d0-0c37-446a-afe3-e4b42a7bfe88)

![Screenshot 2024-12-02 22 56 58](https://github.com/user-attachments/assets/0f81add0-a73f-4eef-80d7-e0672c271385)

![Screenshot 2024-12-02 22 57 10](https://github.com/user-attachments/assets/e72712dd-074b-4768-b770-19b7aafd6b20)

**Comment by yaboidillon** [comment]
Nope, this is what I get:
![Libation command line screenshot](https://github.com/user-attachments/assets/821305e5-cdc1-4214-ac8e-c8bf654b8a6a)

**Comment by rmcrackan** [comment]
From here on, if I sound at any point like I'm assuming you're missing something obvious -- please understand it's because I'm totally out of ideas and I'm grasping at anything I can think of.

Does `C:\Users\Dillon\Libation` contain Libation.exe?

**Comment by yaboidillon** [comment]
It does.
![Libation file explorer screenshot](https://github.com/user-attachments/assets/342d319d-da41-4ebb-99b7-d054ecb2cf82)



I probably am missing something obvious. No offense taken.

**Comment by rmcrackan** [comment]
Much thanks for this screenshot. It looks like this folder contains only Libation.exe and not the other files it needs. When you unzip Libation it has dozens of files around it. Libation.exe needs these to work. After you unzip Libation, you can rename and move that folder but all the files must be kept together in order to work.

**Comment by yaboidillon** [comment]
Okay, I see. Thanks, this was the issue.

I just unzipped the download from earlier of the current version of Libation chardonnay to C:\Users\Dillon\Libation, and it is working now.

**Comment by rmcrackan** [comment]
Thanks for working through the fix with me. I'm glad it's working again.
