### ISSUE TITLE
Fork to add Scraping books from Libro.fm

### ISSUE THREAD

**Issue by dethorpe** [rmcrackan/Libation#1086]
**Is your feature request related to a problem? Please describe.**
I wish to consolidate my audiobook extraction to include my libro.fm account, since I am attempting to shift as much of my purchasing away from Audible as possible.

**Describe the solution you'd like**
I'd like Libation to support the Libro.fm platform. Though I am not yet familiar with the backend of Libation my hope is that it would present somewhat seamlessly with UI. It would hopefully populate as a distinct entry for account (though this would need to be made general from Audible) and titles would list likewise in the main page. Other settings hopefully would be able to consistently applied (file formats, naming, etc) giving the final audiobook library a more uniform feel. Possibly improving on the metadata provided by Libro, as it is pretty sparse.
Libro.fm currently makes titles available for members to download manually, either a number of zip files containing the work separated by chapter in mp3 or a single m4b file with some metadata encoded, there are sometimes pdfs available as well.

**Describe alternatives you've considered**
I currently manually download Libro titles to my Libation (Audible library) directory after purchase and after they convert to m4a.

**Additional context**
I am a very lapsed programmer (graduated with a BS in CS but have a career doing IT.) I'd love to get into contributing to a project like libation and I naively assume this is a pretty simple feature to help add on, given the Libro.fm allows outright downloading titles (although they do not provide a public API.) However given my inexperience I am not sure how to effectively try to contribute beyond pressing the "fork project" button and starting to hack away with the goal of hopefully providing something worth merging into the main project.
Any advice or suggestions further are gratefully recieved.

**Comment by wtanksleyjr** [comment]
I'll wait for the project leads to respond; in the meantime, your enhancement is actually kind of a side feature of Libation (its secondary use as a database for audiobooks). There aren't many good databases for audiobooks, so I understand your input here; but there is one that springs to mind and is actually more centered on collecting audiobooks regardless of their source: Audiobookshelf. You might want to assess whether setting that up might be a quicker path to what you want.

**Comment by dethorpe** [comment]
I do host audiobookshelf which points at my Libation data dir, which is why I manually place my Libro titles there.

IMHO don't think the "side feature" of a Libro title scrapper sits closer to them though then to Libation (as an Audible title scrapper tool.) I find more common cause with Libation in trying to import the books from their sources and matching similar formatting and other settings available here then I do when I think of slapping together some singular html parsing cronjob...

**Comment by rmcrackan** [comment]
Libation's grid looks a whole lot like media management apps like iTunes. However the goal is entirely different. It is not a general purpose audiobook manager, although that could be a cool expansion in the future. Libation's goal is to give users full control over their audible books. To that end, once drm is removed, users are encouraged to do anything they want with those titles, including moving them somewhere that Libation can't find them or removing them from Libation altogether.

Libation's meta-goal is to stick to what it does best and leave others to do what they do best. I don't want Libation to be a mediocre audiobook manager. Other people already do media management way better. Until Libation expands to be a serious contender in that field, I do not want to a book import feature. If you're willing to take on that project, it could be pretty awesome -- but get ready for some serious refactoring and edge cases.

**Comment by dethorpe** [comment]
@rmcrackan, I totally agree. Are we talking past each other?

I don't use or want to use Libation as a media library. Just as the excellent scraping import tool it is. You have already built out a robust set of functions for automatically and uniformly formatting the files you are scrapping for source, that is what I would like to leverage and add to, getting books from another source. 

I do understand though a drive at keeping your project's scope tight and not wanting to take on the specter of supporting the parsing out and downloading the books from Libro and whatever convolutions their site might go through at the same time as Amazon/Audible continues their own. After all if you add one more source, then why not Overdrive? Why not Hoopla? 

I wish there was some way to build another audiobook scrapping tool without starting from the ground up and silo-ing our work. I appreciate everything you've done and I doubt I can get a fraction as far.

**Comment by CharlieRussel** [comment]
And honestly, @rmcrackan, I, for one, don’t want your focus to change. I much prefer a single focus application that does that one thing really well, to a more general application that doesn’t do anything really well. Focused quality over mediocre broad-based functionality.

**Comment by rmcrackan** [comment]
> I totally agree. Are we talking past each other?

Sounds like it. I'll re-read your orig request.

In it's current incarnation, Libation can really only support audible. There are a lot of audible-specific details throughout which would have to change. The biggest one is that audible's IDs are fundamental in the database which drives everything; theoretically you might be able to get away with using a different string here. All communication with the service, from logins to metadata retrieval to book downloads -- all assumes the API calls and structs that have been reverse engineered from the non-public audible API.

I could go on but that would just belabor the point. Since Libation evolved around audible, it is deeply audible-centric even though I never really intended it to be. If I could start all over again, maybe I'd be more diligent about keeping Libation's internals service-agnostic.

I'm going to close this ticket because unfortunately the answer has to be that there's no convenient way to increase Libation's integration with any other service in the short or medium term. I'd certainly love to see someone else succeed in doing so.

Feel free to fork it and poke around. I'll be happy to answer any questions and I'll be notified of all replies here after it's closed.

**Comment by CLHatch** [comment]
> @wtanksleyjr, great point and I do host audiobookshelf which points at my Libation data dir, which is why I manually place my Libro titles there. That does not address the need to automatically import and format for source. IMHO don't think the "side feature" of a Libro title scrapper sits closer to them though then to Libation as an Audible title scrapper tool.
> 
> I even find more common cause with Libation in trying to import the books from their sources and matching similar formatting and other settings available here then I do when I think of slapping together some singular html parsing script kiddy cronjob...

I would suggest instead of manually placing your Libro titles in your Libation folder, that you just add your Libro folder to your Audiobookshelf library.  Don't know if you noticed, but a single Audiobookshelf library can point to more than one folder.  I personally have my audiobook folders set up as `M:\Books\Audiobooks\Audible\<Owner>\books...`, plus  `M:\Books\Audiobooks\Other\books...`  I have several folders added to my main ABS library.  So I would suggest doing the same for your Libro books.  If you mix all the books from several sources together, you won't know later where the book came from.

![image](https://github.com/user-attachments/assets/53dd62ac-5b6b-487e-9cb3-109a3509b870)

**Comment by dethorpe** [comment]
>There are a lot of audible-specific details throughout which would have to change.
I understand completely. Grepping through the project there certainly are useful components, looks like a lot in LibationFileManager, and your writing style is pretty compressible to someone who hasn't attempted a project since college. 

Too bad it can't be as easy as I'd hoped.

> I would suggest instead of manually placing your Libro titles in your Libation folder
Good point. Thank you. It sounds like there isn't an easy way to leverage just the portions of this project needed. This is certainly the next best thing.
