### ISSUE TITLE
Ability to create separate library location presets

### ISSUE THREAD

**Issue by ElysiumFic** [rmcrackan/Libation#1100]
**Is your feature request related to a problem? Please describe.**
I have to different "libraries" I try to create with my downloads, one of a certain genre that I have a massive quantity of books for, and one for everything else. I need to split them up because a) it becomes to hard to find the books that AREN'T in that genre when they are mixed in with the ones that are, and b) AudiobookShelf apps start to get pretty slow when your library is too large, so it's helpful to be able to split them up.

The problem is, this requires going through all my Audible books in Libation, finding the ones that go in the "other" library, setting the download location for one place, waiting for them all to download, and then changing the download location to somewhere else for the primary-genre-specific library and downloading all of those books. And in the process discovering the ones I missed the first time around and having to download those to somewhere else. I'm not describing it well, but it's a whole thing that's a big annoyance.

**Describe the solution you'd like**
Instead of having one download location, I'd like the ability to have a setting for Location Preset 1, Location Preset 2, etc. And then, be able to designate that all books by certain authors or in certain genres or series go to Location Preset 1, while all books by other authors or in other genres or series go to Location Preset 2. 

**Describe alternatives you've considered**
I have been known to download them all to the same location and then move them, but then I have to tell Libation where the files are using "locate file" and that's a pain too.

**Comment by rmcrackan** [comment]
Interesting proposal. It sounds a bit too niche to become a full fledged new feature. I think if you use [naming templates](https://github.com/rmcrackan/Libation/blob/master/Documentation/NamingTemplates.md) for author or series though, you can at least streamline your organization process. (There's intentionally no templating options for genre because audible's genre taxonomy is only ok at the best of times and it's too often a hot mess.)

This might be a job for these naming templates in Libation and then your own custom script after the fact. I'm not a python person but I bet there's pretty quick way in python to search your downloads and move things to location A vs B based on some simple criteria.
