### ISSUE TITLE
5.7.3 appears to still have the issue referenced in #113

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#114]
I'm still getting silent crashes in 5.7.3 -- the same behaviour as last night with 5.7.1 and reported in #113. For now, I've gone back to an older build (pre-CLI).

**Comment by rmcrackan** [comment]
This is wacky! I just downloaded it on my computer and it works fine from that .zip. I can't imagine what is causing it to fail on some computers and not others. Can you verify that this bug happens for you every time with the 5.7.3 zip?

**Comment by rmcrackan** [comment]
Thank you so much for testing it so thoroughly. I'll have to pull CLI and find a different way to deploy

**Comment by rmcrackan** [comment]
In [the latest release: v5.7.4](https://github.com/rmcrackan/Libation/releases/tag/v5.7.4) I figured out a new way to repackage which still includes Libation.exe and LibationCLI.exe in the same folder so they can share settings, db, etc. Per the release notes, since this issue was intermittent across users, I can't be 100% sure it's fixed. Please let me know if either program does not run for you.
