### ISSUE TITLE
Crash if disk full

### ISSUE THREAD

**Issue by jbscout** [rmcrackan/Libation#115]
LIbation crashes if I have run out of disk space.

A bit of a user error really, but a dialog box instead of a crash would be nice.

Thanks

**Comment by rmcrackan** [comment]
Sorry it crashed on you.

I actually did research this edge case but the complexity wasn't worth it. The current error logging architecture is built around the idea that if something goes wrong then we want to write it to disk. On disk full, a 'disk full' error happens so we tell the error logger to write the error to disk ... but then that cascades another error since there's nowhere to write. When we get 2 layers deep into logging we know something is deeply wrong. At this point we try to be a good citizen and just let windows shut us down.
