### ISSUE TITLE
aaxc files

### ISSUE THREAD

**Issue by 1andy981** [rmcrackan/Libation#156]
Hi, I saw your posts in reddit, but not registered there.  when I check the box to add podcasts to import I get the errors, logs attached.  

do you think the plus library aacx files will ever work with libation?  i would love to have some of those podcasts on my walkman.
[_Log202111.log](https://github.com/rmcrackan/Libation/files/7562299/_Log202111.log)

**Comment by 1andy981** [comment]
i am basically trying to get an exclusive plus library podcast onto my device.  I pay for audible and they stop downloading.  Drives me crazy

**Comment by 1andy981** [comment]
sorry, just found out that your latest version (from reddit) does include podcasts and plus library.  so hopefully my log shows the issue with mine

**Comment by rmcrackan** [comment]
Thank you for the log file. If you close Libation and try again, do you get the same errors?

**Comment by 1andy981** [comment]
Hi, yeah, same errors even if logged off and on again.  Found an old version that works though.  On 19 Nov 2021 16:21, rmcrackan ***@***.***> wrote:
Thank you for the log file. If you close Libation and try again, do you get the same errors?

**Comment by rmcrackan** [comment]
It sounds like a book got added to the database twice. This isn't supposed to be possible which means there's a bug somewhere. I'll look for it. In the meantime, you can probably fix the error by closing Libation, re-naming the LibationContext.db database file, and doing a fresh import. A new database will be automatically created.

The database keeps track of liberated status. A new database means that previous liberated statuses will be lost. You could either [a] download your books again [b] manually change the status of previously downloaded books from 'not liberated' to 'liberated' [c] you can zip and [email](https://github.com/rmcrackan) me both the old and the new database files and I can update it for you (since this is my goof).

**Comment by 1andy981** [comment]
Thank you, I've got the books I wanted, well podcast.  I loved the app, will be grabbing series 3 that way too and definitely leaving a tip!  On 19 Nov 2021 18:09, rmcrackan ***@***.***> wrote:
It sounds like a book got added to the database twice. This isn't supposed to be possible which means there's a bug somewhere. I'll look for it. In the meantime, you can probably fix the error by closing Libation, re-naming the LibationContext.db database file, and doing a fresh import. A new database will be automatically created.
The database keeps track of liberated status. A new database means that previous liberated statuses will be lost. You could either [a] download your books again [b] manually change the status of previously downloaded books from 'not liberated' to 'liberated' [c] you can zip and email me both the old and the new database files and I can update it for you (since this is my goof).

**Comment by rmcrackan** [comment]
Very kind of you. Sounds like this issue is resolved so I'll close this out. Enjoy your books/podcasts!
