### ISSUE TITLE
"Books location: \\xxx.xxx.xxx.xxx\directory\subdirectory" doesn't seem to work any more

### ISSUE THREAD

**Issue by Mulchman** [rmcrackan/Libation#157]
I have my "Settings" > "Settings" > "Book location" set to a folder on the network in the format "\\192.168.xxx.xxx\xxx\xxx" and this worked up until a few versions ago:

![image](https://user-images.githubusercontent.com/11757993/143131076-a90ef855-a709-46c7-9884-6f4f658cb603.png)

Now, liberated books end up getting put in "D:\192.168.xxx.xxx\xxx\xxx" instead:

![image](https://user-images.githubusercontent.com/11757993/143131206-244fceec-5097-4c1d-a56c-7821660ffb1d.png)

(Libation lives at "D:\Libation.x.x.x\libation.exe" in case it being on the non-root C drive is also a contributing factor.)

**Comment by rmcrackan** [comment]
My bad. I intentionally get rid of double slashes in the new custom paths. It's necessary so empty fields don't try to create buggy folders with non-names. Eg: `<author>\<series>\<narrator>` , no series => `Mr Author\Miss Narr` instead of `Mr Author\\Miss Narr`. I forgot to leave them alone at the start of paths. D'oh! Thanks for catching this. Fixed in [v6.5.1](https://github.com/rmcrackan/Libation/releases/latest).

I don't currently have access to a UNC path dir so I can't test the fix. Please report back if it's still broken in v6.5.1

**Comment by CharlieRussel** [comment]
FWIW, @rmcrackan, you can test this using the good old \\\127.0.0.1\\<share> or \\\localhost\\<share> method for a UNC.

**Comment by Mulchman** [comment]
Thanks, it's working again.
