### ISSUE TITLE
If you get your password wrong, it cycles captcha forever

### ISSUE THREAD

**Issue by L0garithmic** [rmcrackan/Libation#159]
If you get your password wrong, it cycles captcha forever
Something to keep in mind, no way to know it was password.

**Comment by rmcrackan** [comment]
The login with amazon has been a battle and a half. And since Libation is not a sanctioned program, I can't get any help from them. I think I've reached the limits of my ability to beat their login system into submission and this is as good as I can make it.

Although this problem is valid, I'm going to close the 'issue'. There's little more I can do beyond what I've already done so keeping this open as a to-do item isn't productive.

**Comment by L0garithmic** [comment]
K sounds good. Maybe just add a note then. Thanks!
