### ISSUE TITLE
Save cover image along side audio book

### ISSUE THREAD

**Issue by BigGuyWithBeard** [rmcrackan/Libation#182]
Hi, 
Can we have an option to save a jpg next ot the audio book, eg folder.jpg.  then in windows explorer, we can see thumbnail of the book cover.

**Comment by rmcrackan** [comment]
@Mbucari I swear I saw this when I was reviewing the PR but now I don't see this new setting. Am I going nuts?

**Comment by Mbucari** [comment]
I didn't add a setting for it. Libation saves a full size image for every book it downloads.  Probably should make it optional, huh.

**Comment by Mbucari** [comment]
The picture download method is in FileLiberator.Processable, but it probably should be in FileLiberator.DownloadDecryptBook because that's where all other config options are read and executed.

**Comment by rmcrackan** [comment]
Yeah, it would be better as optional. And I assume it should be named the same as the file. Or the book title in the case of chapterized. RE location: you're probably right there also. You've been in that part of the code a lot more recently than me. If you have another change in you, go for it. Otherwise, it might just have to wait until ... who knows.

**Comment by Mbucari** [comment]
Yea, I'll do that here soon.  I also had something else in the pipe that's nearly ready.

**Comment by rmcrackan** [comment]
@BigGuyWithBeard this is technically in the current version now (non-optional) and in the next version it will be available as an optional setting. So I'm going to close out this issue
