### ISSUE TITLE
Request- .aax to .m4b converter with chapter name.

### ISSUE THREAD

**Issue by Kumarashantanu** [rmcrackan/Libation#220]
Previously I have downloaded lots of .aax files, I removed DRM using inaudible. The drawback of inAudible was Chapter names, I don't own audiobooks now, I have only .aax file. Is it possible to convert those to m4b with the proper Chapter Name?

**Comment by rmcrackan** [comment]
Sorry, that's not possible. Those come indirectly from your audible account. If you still owned these books on audible, then for each book Libation could ask audible for your license details then use that to ask for the chapter details for the book. That information isn't stored in the aax file itself and there's no way to ask audible for chapter details when you don't own the book.

**Comment by Kumarashantanu** [comment]
Thank you so much for your response

**Comment by mkb79** [comment]
@rmcrackan 

> That information isn't stored in the aax file itself and there's no way to ask audible for chapter details when you don't own the book.

You can use [this](https://audible.readthedocs.io/en/latest/misc/external_api.html#get-1-0-content-asin-metadata) endpoint to request the chapter infos for books. This works for books which you don’t own, too!

Best regards

**Comment by mkb79** [comment]
@rmcrackan --I'm was not sure, so I've tried it out myself. This endpoint can be requested without authentication!

**Comment by Mbucari** [comment]
@Kumarashantanu 
Do you still have your activation bytes for you AAX files?

**Comment by Kumarashantanu** [comment]
@Mbucari Sorry, I have no idea what that is. I just have AAX files and I am still able to remove the DRM and convert it to mp3/m4b in Inaudible software.

**Comment by Mbucari** [comment]
@Kumarashantanu 
How much customization are you looking for?  Just a simple 1-click aax -> m4b with proper chapter names? Or something more complex like splitting into multiple files, editing metadata, converting to mp3, etc.?

**Comment by Mbucari** [comment]
I made a new project for downloading chapter from audible servers and saving them as .cue files.

[Check it out here](https://github.com/Mbucari/AaxChaptersCue/releases/tag/v0.1.0).

It's very basic, but by the sound of it you don't really want much more.

Just run the program and drag-drop aax files into it.  It will download the chapters for each file and save them as a .cue file in the same folder as the aax files.

**Comment by Kumarashantanu** [comment]
@Mbucari this works wonderful, Thank you so much. 👍🏼 -)

**Comment by rmcrackan** [comment]
@Kumarashantanu Since this is working for you, I'm going to close this issue for now. Mbucari and myself will still see all replies.

@Mbucari Sounds like you created a great tool. What's your opinion on if/how to integrate your new tool into Libation? It almost feels like Libation is evolving into a suite of tools. (Which of course gets my architect brain going wild with plugin-like possibilities but I don't want to get too ambitious yet.)

**Comment by Mbucari** [comment]
> What's your opinion on if/how to integrate your new tool into Libation?

I gave this some thought before deciding to make it a standalone project, but ultimately decided against it. There are a plethora of tools for working with aax files because the decryption keys are account-specific and easy to get, either by rainbow tables or the api. This tool would be a great addition to any workflow using those tools. But for aaxc files to be usable, they must be downloaded with something like AudibleApi or audible-cli because the decryption key is file-specific. And if you're downloading them with a full client like AudibleApi or audible-cli, then you already have easy access to the server's chapter markers. So this tool is really only useful for aax files, not aaxc files. But aax is now legacy. The windows app is going away, and the mobile apps ONLY download aaxc files. Pretty soon you won't even be able to download new aax files. Thus, I don't see a long-term use for this or any other aax-only tool.

> It almost feels like Libation is evolving into a suite of tools. (Which of course gets my architect brain going wild with plugin-like possibilities but I don't want to get too ambitious yet.)

I had this exact thought recently (great minds, eh?).  I'd love to try my hand designing a plugin api! But any useful plugin api will interact with the UI, so I don't want to do any work on that until xplat is done.  And speaking of xplat, that's going to be my next project.  I plan to start with the main form (because if I can't make that work, why bother with anything else?).  Once Form1 ported, I'll make a PR so you can review and help me debug.

**Comment by rmcrackan** [comment]
> I don't see a long-term use for this or any other aax-only tool

Sounds good

> plugin api

I did one of these in my first professional programming job. They're a really compelling set of challenges. I think it's overly ambitious for what we have now. It's fun to imagine though. Another fun but crazy overly ambitious project: adding scripting. It brings very little real world user value (and user support is nightmare and a half!!!) but damn is it fun to architect.

> xplat

You can make new stuff, just don't get rid of any winforms until we're ready to make a full switch.

What framework were you looking at? Also, is AAXClean xplat?

**Comment by rmcrackan** [comment]
btw -- I implemented your publish stuff in my release tool. I've tested it and will use it from here on out. Huge file size improvement.

old sizes  
zipped 70.5 MB  
unzipped 164 MB

new sizes  
zipped 22.5 MB  
unzipped 52.4 MB

**Comment by Mbucari** [comment]
> but damn is it fun to architect.

Isn't that the whole point of hobby projects like Libation?

> don't get rid of any winforms until we're ready to make a full switch.

That's the plan.  I'm going to wire it up in Main() so you can easily swap between winforms and whatever I come up with.
> What framework were you looking at?

I'm going to try Flutter. Avalonia looks cool, and if Libation was already written in WPF it would be an easier port. But I HATE working with xml layouts, so flutter may be more my speed.

> Also, is AAXClean xplat?

It is, but AAXClean.Codecs is not. It uses native libs to decode aac to wave and to encode wave to mp3. The lame mp3 lib is already compiled across pretty much every platform imaginable, so that's not a problem. I wrote the aac decoder lib, which is based on ffmpeg 4.3.  FFMpeg is already xplat, so I just need to figure out how to compile my lib on mac/linux.

**Comment by Mbucari** [comment]
> publish stuff

Did you notice the speed increase? ReadyToRun actually works, so the UI is much more responsive from the get-go.
