### ISSUE TITLE
App freezing during import: log says it received a timeout

### ISSUE THREAD

**Issue by badbob001** [rmcrackan/Libation#222]
Not sure why it's not handling the timeout and moving on to the next item. When this happens, the download progress window is gone, leaving only the 'Automated Backups' log window and the main catalog window.
[Log202204.log](https://github.com/rmcrackan/Libation/files/8419070/Log202204.log)

Is there a way to influence the order of the full imports other than to manually click individual titles? Seems like this podcast is problematic and so I want to download everything else first. Can I use the Remove from library option to remove the problematic items, do a full import, and then do a library scan to get back those deleted items?

**Comment by rmcrackan** [comment]
> Can I use the Remove from library option to remove the problematic items, do a full import, and then do a library scan to get back those deleted items?

Yeah, that's probably your best option. Fortunately, since this is a podcast, you could unsubscribe, run the 'remove from library' (which will auto detect those missing items), do the scan and import, then when it's all done you can re-subscribe.

You could also manually change anticipated problem items to 'downloaded' and avoid them all together. It's the button on the right side of the book's row.
