### ISSUE TITLE
Refuses Captcha 

### ISSUE THREAD

**Issue by Ironlily69** [rmcrackan/Libation#226]
No matter what I do it refuses to accept the captcha  or it has 2 rows and only half of the second is visible
my email is correct my password is correct and still

**Comment by CharlieRussel** [comment]
Use the web browser workaround for the captcha. I had the same issue with the built in one, but the web workaround solved it.

Sent from Outlook<https://aka.ms/qtex0l> on my phone. Please excuse any terseness or Autocorrect typos.
________________________________
From: Ironlily69 ***@***.***>
Sent: Saturday, April 9, 2022 10:46:19 AM
To: rmcrackan/Libation ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rmcrackan/Libation] Refuses Captcha (Issue #226)


No matter what I do it refuses to accept the captcha or it has 2 rows and only half of the second is visible
my email is correct my password is correct and still

**Comment by Ironlily69** [comment]
I am not aware of what the work around is. I reset my network  worthless  Excuse my ignorance  *sigh*

**Comment by rmcrackan** [comment]
Every once in a while, someone will get caught in an endless captcha loop. I have no idea why :(

In Libation: Delete your account. Save. Re-add. Save. Scan. If you did this correctly, it will prompt you for your password. Instead of typing your password, click the link that says "Or click here". It will explain the other login method that @CharlieRussel mentioned.

**Comment by CharlieRussel** [comment]
@rmcrackan:  we should probably add a paragraph somewhere in the “documentation” for that. I looked to point him at it, not being at my desktop to recreate it, but there wasn’t anything to point to. I can write something up if you want?

Sent from Outlook<https://aka.ms/qtex0l> on my phone. Please excuse any terseness or Autocorrect typos.
________________________________

**Comment by rmcrackan** [comment]
@CharlieRussel Thanks, that would be great then I can update the readme. If you know how to submit a Pull Request, you're welcome to edit the readme directly.

**Comment by CharlieRussel** [comment]
I know how, but honestly it’s theoretical. I’m a writer and IT pro. Not a developer. Though I have been known to write a fair amount of PowerShell.

I’ll write up something tomorrow.

Sent from Outlook<https://aka.ms/qtex0l> on my phone. Please excuse any terseness or Autocorrect typos.
________________________________

**Comment by Ironlily69** [comment]
Thanks You
That is what I did I hunted down everything deleted it,  restarted then re
installed
It took this time

**Comment by rmcrackan** [comment]
Glad to hear it. Thanks for checking back in

@CharlieRussel I'm going to close this issue but you can still reply here; I'll still get the 'new message' notices

**Comment by CharlieRussel** [comment]
@rmcrackan: Please add the text and images between the ---- lines to the readme.md immediately below "Or if you have multiple accounts, you'll get to choose whether to scan all accounts or just the ones you select:" and the image associated with that paragraph.  (Sorry, but it appears to have pasted the images full size. You'll likely want to scale them a bit.)
-------------------------------------------------
If this is a new installation, or you're scanning an account you haven't scanned before, you'll be prompted to enter your password for the Audible account.
![image](https://user-images.githubusercontent.com/21000516/162635529-fdebc5b8-4cc0-4d9a-ac72-4aca7140c8de.png)
Enter the password and click Submit. Audible will prompt you with a CAPTCHA image. 

![image](https://user-images.githubusercontent.com/21000516/162635565-3c4a0444-8678-4226-9e0b-26763c1eff24.png)

Enter the CAPTCHA answer characters and click Submit. If all has gone well, Libation will start scanning the account. 

In rare instances, the Captcha image/response will fail in an endless loop. If this happens, delete the problem account, and then click Save. Re-add the account and click Save again. Now try to scan the account again. This time, instead of typing your password, click the link that says "Or click here". This will open the Audible External Login dialog shown below.

![image](https://user-images.githubusercontent.com/21000516/162635696-6b43e77c-eb92-454f-96f6-0a38dad47646.png)

You can either copy the URL shown and paste it into your browser or launch the browser directly by clicking Launch in Browser. Audible will display its standard login page. Login, including answering the CAPTCHA on the next page. In some cases, you might have to approve the login from the email account associated with that login, but once the login is successful, you'll see an error message.

![image](https://user-images.githubusercontent.com/21000516/162635708-13325b08-381a-46d5-a09f-777d0308010b.png)

This actually means you've successfully logged in. Copy the entire URL shown in your browser and return to Libation. Paste that URL into the text box at the bottom of the Audible External Login window and click Submit.
-------------------------------------------------

**Comment by rmcrackan** [comment]
@CharlieRussel Thanks! It's live now. Is this what you had in mind? Also: you're a writer -- yay! I'm a strong backend developer but I'm emphatically not a designer, UX expert, or a writer. Do you have any advice for my front page? I need to keep useful info front and center for new users, but not have the abysmal eyesore that it is currently.

**Comment by CharlieRussel** [comment]
Yes, exactly what I had in mind.

As for the overall look and feel of the front page, I hadn’t really thought about it. You’re pretty clear with your good/bad/ugly, and I took it as it came. I was just trying to help a bit by having instructions we could point to for those who get stuck in that whole captcha loop.

Perhaps moving to having the documentation off the front page? With a link to it there?  Or more like, say, Calibre uses, or a wiki like interface?  But really, it’s not what you are, and I’m not sure how far you want to go with this.

Sent from Outlook<https://aka.ms/qtex0l> on my phone. Please excuse any terseness or Autocorrect typos.
________________________________
