### ISSUE TITLE
General questions (upgrading, usability)

### ISSUE THREAD

**Issue by Mulchman** [rmcrackan/Libation#23]
Hi, this isn't a bug report and I don't want to hound you on Reddit with a ton of questions/requests so I thought I'd put things here. All of these sections kind of build on top of each other as you'll see when reading.

----

1. Upgrading?

What's your recommended upgrade process from version to version of Libation? I'd like to upgrade "in-place" rather than making a new directory for the new version but upon diffing the 2 versions it looked like some of the json files changed (and changed formats) and I didn't want to deal with any hassles that might create so I simply created a new directory for 4.19, went through the set up process again, pointed everything to where the audio books live on my hard drive, and then was off and running. It'd be way more convenient if the new version could just be extracted over the old version.

----

2. Removing files from hard drive but still knowing the books are liberated?

(This feature might exist but I don't want to delete books from my hard drive yet to test it.)

I'd like to not keep all the books on my hard drive and instead just have the program know/remember what I've already 'liberated' and what I haven't. Right now I think the app knows what I have 'liberated' by looking at my hard drive and comparing the directories w/ the audible keys in their names against a list it downloads from audible. I want to not have the files on my hard drive but still have the app know what's been 'liberated' and what hasn't AND also have this work across version upgrades (especially if new directories have to be created for new versions). Some kind of .json file I can copy over w/ all the audible keys in them - or writing this to a Libation directory under %appdata% so it can be persisted across any directory deletes - and the app can see those and make them 'green' in the UI to indicate they've already been 'liberated' and all that.

----

~~3. Boolean filter option to know what's liberated and what's not?~~

~~(This might exist as a filter option but none of the ones I've seen or tried do what I'm asking for.)~~

~~I'd like to have a filter "IsLiberated" or something (that I can then negate -> !IsLiberated) to see a list of what new books I've bought that haven't been 'liberated' yet. I have 200+ books currently and the UI list gets very daunting to look at. My process of using the app is: buy new books on Audible, open Libation, 'Import > scan library', 'Liberate > Begin book backup...', close application, copy to phone, listen. (I want to add a delete step in there but go back to section 2 where I think the files need to live on my hard drive for the app to know whether it's been 'liberated' or not.)~~

I'll push a PR for this later. Can't remember my credentials to push to git at the moment.

----

~~4. Building the app myself / directory layout?~~

~~I ended up getting things to build. The directory structure required an extra directory in front of 'AudibleApi' called "audible api". After getting the hierarchy right everything *seems* to build okay.~~

----

Thanks for reading.

**Comment by rmcrackan** [comment]
Sounds like you're a developer so that'll make this conversation a lot easier.

> Upgrading

You're correct that install in place would be much more useful. No plans to do it though because whenever I find the time, there are too many things ahead of it in priority. Especially because I've written auto-installers before and the edge cases are non-trivial. Convenient, but not enough of a time vs rewards tradeoff.

When you unzip the new version, everything that the program needs is in that folder with the correct files and dir structure. This can be moved anywhere you want. appsettings.json contains the absolute path to the "LibationFiles" dir which will contain all mutable files, database, tokens, logs, etc. LibationFiles \ Settings.json "Books" points to where you keep your books. It sounds convoluted but what this allows is for the app to be kept in one location that Libation doesn't need access to modify, all of the settings are in 1 place, and you can store your media files anywhere else.

> Removing liberated files

I've gone back and forth on this one. I see your point. I also like knowing if a file has been accidentally deleted (which has happened when a family member who shared my dropbox acct moves my stuff). For now there is no such feature. Libation looks for an audio file with the audible id appears in their path. When Libation decrypts the audible file, it exports a m4b file. I assume many people might use another program to convert it to a more common format so I also look for other common audio file extensions.

There is a very manual hack but likely not one you'd want to do for any large volume. It also looks for the extension .libhack -- so you could create the file c:\my books\B06WLMWF2S.libhack . It wouldn't be too hard to write a program to create these files for you, but it's not built into Libation

> Search filter for liberation status

Damn, I can't believe I never thought to do that. Great idea. Adding this to search is possible but not trivial. [1] Liberation stages don't currently fire off search engine re-indexing. Currently, a full re-index is done after you import/scan your library. And a more surgical indexing happens when you edit tags. [2] The search engine doesn't know anything about these stages. [3] After those enhancements are made, a new rule could be written for the search engine.

> Code structure

I hate git's way of doing submodules so I use the hack of keeping 3 repos and manually linking them in the sln/csproj files. The repos are Dinah.Core , AudibleApi , Libation. All are available on my github acct

Since this isn't an actual bug report, I'm closing this issue. You can still reply and we can continue the conversation though.

**Comment by rmcrackan** [comment]
Oh yeah, the LuceneNet303r2 repo is also in my github.

I recommend deleting GitAllRepos. This is a program which searches the local git repos for any uncommitted files. It's my embarrassing work around of keeping my code in separate repos but in the same sln

**Comment by Mulchman** [comment]
> Damn, I can't believe I never thought to do that. Great idea. Adding this to search is possible but not trivial. [1] Liberation stages don't currently fire off search engine re-indexing. Currently, a full re-index is done after you import/scan your library. And a more surgical indexing happens when you edit tags. [2] The search engine doesn't know anything about these stages. [3] After those enhancements are made, a new rule could be written for the search engine.

Ah, so there's much more to it than simply a couple of lines in `SearchEngine.cs`-

`["IsLiberated"] = lb => FileManager.AudibleFileStorage.Audio.Exists(lb.Book.AudibleProductId),`
`["Liberated"] = lb => FileManager.AudibleFileStorage.Audio.Exists(lb.Book.AudibleProductId),`

I'll poke around and see if I can figure out [1] & [2] then get back to you.

**Comment by rmcrackan** [comment]
Technically that would absolutely work, but your 'worst case scenario' performance would be abysmal. Instead of looking inside the search engine's index, all IsLiberated searches would traverse your file system live for each title. For liberated titles this is really fast since it's cached elsewhere. For EACH cache miss, it would recurse through the entire dir tree starting with your "Books" directory. If your dir structure is pretty flat, your code would be a good solution. For the general case though, I'd definitely want to use the index

**Comment by Mulchman** [comment]
Gotcha. `GridEntry.cs` is checking the disk for every book (sometimes twice) - is that something you'd want to improve as well?

**Comment by Mulchman** [comment]
And I should clarify - for the `IsLiberated` methods I'm spit-balling they'd be `{ get; private set; }` and not doing the disk check when called. (IDK when the disk check value would be initially set/cached, either, just mentioning it so you don't think I'm suggesting to have the disk check in the getter every time it's called.)

**Comment by rmcrackan** [comment]
> GridEntry.cs is checking the disk for every book (sometimes twice) - is that something you'd want to improve as well?

The thing about exposing your code to the world ...is that you feel really exposed. Yeah GridEntry is some sloppiness which dates back to version 1. I’ve cleaned up a lot of that area but there are still a few ugly vestiges such as what you found.

For IsLiberated, I was thinking over dinner: I’m going to have to commit to a single model -- either cached as per the search index OR calculated live as with the grid. What I described earlier today would leave the model inconsistent. If I opt for live, then your prev method is perfectly workable and would be consistent with the grid. If cached, then I'd need to rework the grid anyway. Also, it's really just for you at the moment (although I'll lie to myself and say I'll refactor it later) so if it's good enough for your use case, I can probably throw that together pretty quickly.

If eventually refactored into something less ephemeral, it could live any number of places including what you mentioned. For now though, I'm leaning toward the 'live' version.

**Comment by rmcrackan** [comment]
Check out v4.2.0 :)

**Comment by Mulchman** [comment]
Awesome, thanks! Tag works great. :)

**Comment by rmcrackan** [comment]
v4.2.1 has some performance improvements and a bug fix surrounding this new filter

https://github.com/rmcrackan/Libation/releases/latest
