### ISSUE TITLE
7.10+ does not update grid with new books after library import

### ISSUE THREAD

**Issue by flysalad** [rmcrackan/Libation#270]
Versions 7.10.2 and 7.11 both fail to update the grid to show new books when using the import function. I have to restart Libation to get the grid to show the new books. Other functions I use seem to be fine.

[Log202206.log](https://github.com/rmcrackan/Libation/files/8883081/Log202206.log)

**Comment by Mbucari** [comment]
@rmcrackan This one is a bit sticky.

The offending episode (of course it's an episode) is B01ERWOYXU. It's in his library, but it has been removed from audible.

The way Libation retrieves parents for individual episodes is by looking for parent's asin in the episode's relationships, querying the parent from the catalog api endpoint, then adding the parent to the database. Prior to 7.11, individual episodes weren't assigned a series with a parent asin. This isn't a problem when episodes are still in the user's library, because a fresh library scan will find and add the series. The problem for him is that episode is no longer on audible, so its db entry has no series link with parent asin, and we'll never be able to find it again.

Moving forward as audible removes more episodes from podcasts, this will not be a problem because the episodes' series link will already have been added to the db.

But for this legacy problem, the only way I can think to handle this is to add a catch-all series for orphaned episodes. Maybe add it in a migration.

**Comment by Mbucari** [comment]
@flysalad Can you please share your LibationContext.db file with me? I'd like to see how your episodes are being stored after 2 attempts to fix this problem.

The file contains all your library books, custom tags and liberated status, but no personally identifying information.

**Comment by flysalad** [comment]
Zipped LibationContext.db atttached, as requested.

[LibationContext.zip](https://github.com/rmcrackan/Libation/files/8883258/LibationContext.zip)

**Comment by Mbucari** [comment]
Thank you @flysalad. And please delete that link, as I was wrong, it does contain your email address. Sorry! The DB guy is asleep.

**Comment by Mbucari** [comment]
@rmcrackan 

OK, there's are even more legacy issues here than I realized. So back in the day before podcasts were supported, all items that were IsEpisodes were discarded from the import operation.  But for a long time, IsEpisodes worked like:

```C#
=> Relationships?.Any(r => r.RelationshipToProduct == RelationshipToProduct.Child && r.RelationshipType == RelationshipType.Episode)
			?? false;
```

Remember [my explanation of relationships](https://github.com/rmcrackan/AudibleApi/pull/28#issue-1263872961)? By only checking if an item had a relationship to a child, the importer:

- Added podcast series and seasons as books with ContentType.Episode
- Created a Series with the same asin as the book and added to the book

This will require a migration to fix, but I think it is possible.

**Comment by Mbucari** [comment]
@flysalad 

In the Libation program files folder, run Hangover.exe
Pase the following command int the text box and click "Execute"

```SQL
update Books
  set ContentType = 4
    where AudibleProductId in
      (select bks.AudibleProductId from Books as bks inner join Series as sr on (bks.AudibleProductId = sr.AudibleSeriesId)
        where bks.ContentType = 2)
```

After it runs, you should see "12 records affected"

Then run libation, do a scan, and see if it fixed your problem.

**Comment by flysalad** [comment]
I tried running the db commands with Hangover.exe and it reported 12 records affect. Unfortunately, it still didn't update the grid after importing the book.

**Comment by Mbucari** [comment]
@flysalad Yes, there are some other issues that I'll need to fix with a Libation patch. But after running that query you should have noticed there are more podcast series in the grid than before. It helped, but it's not fixed yet.

**Comment by flysalad** [comment]
@Mbucari Definitely more podcast series in the grid, although I unsubscribed from most of them after downloading.

**Comment by Mbucari** [comment]
@flysalad 

I've manually fixed your db. Password is your f***.a***@***  email address

Delete your existing LibationContext.db file, extract this fixed db to the same folder, and rename it to LibationContext.db
[LibationContext-Fixed.zip](https://github.com/rmcrackan/Libation/files/8883697/LibationContext-Fixed.zip)

**Comment by Mbucari** [comment]
@flysalad
any luck?

**Comment by rmcrackan** [comment]
Holy moly I woke up to a lot of updates today. Is my help needed on this bug or do you have it under control?

**Comment by Mbucari** [comment]
I got it. It was a nightmare to debug, but I have definitely solved this one user's problem lol. He hasn't replied if it worked for him yet, but I tested his exact db on my end with existing libation, and the db I fixed for him should work fine in Libation 7.11.

My fixes and the new features are in my pr. Please pa especially close attention to the queries in the migration code. I'm an EF novice, so I don't know if running raw queries like that can be problematic.  This whole process has made me so paranoid.

**Comment by flysalad** [comment]
@Mbucari The fix worked. New books are now showing in the grid after import.

I'm guessing I probably shouldn't ask what the fix involved.

**Comment by Mbucari** [comment]
> I'm guessing I probably shouldn't ask what the fix involved.
Genius and hard work. You know, the usual. 🤣

Seriously though, you have probably the oldest existing libation database file. You have stuff in there from 2020. The software has been through so many design iterations and database migrations that I'm shocked you haven't had to delete it and start from scratch.

**Comment by flysalad** [comment]
Do you recommend periodic DB deletion? I hadn't thought of doing that to fix the problems.

**Comment by Mbucari** [comment]
I wouldn't recommend it unless you have a problem because it does come at a cost. Libation will be able to scan your books folder for any liberated files and update their status even after you deleted a database, but if you've moved liberated files out side of that folder it won't know that they are liberated. Also if you make use of the tags feature, all of those are stored inside the DB and would be lost with the Db deletion. But if you're not troubled by either of those facts, then a DB deletion and rescan might solve your problems in the future. It's certainly would have in this case. I'm just loathed to resort to that because of the aforementioned costs.

**Comment by flysalad** [comment]
@Mbucari Noted. I always move my liberated books so I don't care about the liberated status and don't use tags, so I will keep this in mind if I have problems in the future.

**Comment by rmcrackan** [comment]
> if you make use of the tags feature, all of those are stored inside the DB and would be lost with the Db deletion

You're kinda right.

Originally the database was only stuff from audible so it could be discarded with no consequences. Years ago when I added tags, I made a convoluted system that saves to the database but also stores in another file. When the database is deleted, it will even reload tags from that file. Again: so you could discard it with no consequences. Since then we've also added liberated status. It's now a more proper database and soon I might remove the tags redundancy and other things could be added. For now though the only things solely in the database is liberated statuses and stuff directly from libation.

**Comment by rmcrackan** [comment]
> pa especially close attention to the queries in the migration code

This isn't necessarily a problem. I think migrations are basically the only place we should be using raw sql. It looks good to me. Test the crap out of it. Especially consider: what happens on the 2nd run, or the 10th. Since this migration runs unconditionally on every launch, every user will run this repeatedly. Maybe include a small check at the beginning to see if this is even needed so you can return early in nearly all cases.

**Comment by flysalad** [comment]
@rmcrackan You really should add the migration status/version into a table in the db itself. This way you can see which is the latest version run and that the migration should have already been completed. This would speed up startup slightly.

**Comment by rmcrackan** [comment]
@flysalad Good point. Most db migrations are are handled exactly as you describe. The current fix is an anomaly but it would make sense to handle it either way. The benefit to the alternative being used here is that if something goes wrong, we can exit this 'migration' gracefully without risking bricking the app for the user.

**Comment by rmcrackan** [comment]
Fixed in [v8](https://github.com/rmcrackan/Libation/releases/latest)
