### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rdow64** [rmcrackan/Libation#286]
[_Log202202.log](https://github.com/rmcrackan/Libation/files/8950420/_Log202202.log)

**Comment by Mbucari** [comment]
@rdow64 You appear to be running version 6.6.7.2, which is quite old at this point and no longer supported.  Can you try upgrading to the latest release? Also, I don't see any crash info in your log file.  Libation has much better logging now than it did back then, so if you upgrade and still have this error, your log files will be much more useful.

**Comment by Mbucari** [comment]
Try deleting all log files in your libation folder.  If it happens again, post the newly-created log file here.

**Comment by rdow64** [comment]
Sorry for the confusion, but I dd find the actual log file with today's date and it is attached.

    On Tuesday, June 21, 2022 at 02:23:25 PM CDT, Mbucari ***@***.***> wrote:  
 
 


Try deleting all log files in your libation folder. If it happens again, post the newly-created log file here.

**Comment by rmcrackan** [comment]
Sorry, the attachment didn't come through. Maybe you have to come to the github page to attach it.

**Comment by anthonynogales** [comment]
[Libation has encountered an unexpected error.txt](https://github.com/rmcrackan/Libation/files/8959573/Libation.has.encountered.an.unexpected.error.txt)

I got this error a few minutes ago while downloading a book with a PDF. The line that stuck out to me was:
`at FileLiberator.DownloadPdf.downloadPdfAsync(LibraryBook libraryBook, String proposedDownloadFilePath) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\FileLiberator\DownloadPdf.cs:line 61`

**Comment by rmcrackan** [comment]
I mean *YOU'RE* welcome to see it. It's in that account settings file and is needed to communicate with audible. The rest of us though, including me, not so much. Fortunately, this stuff expires about once an hour and the "refresh token" is used to get a new batch. Even still, I'm really security conscious and this doesn't sit well with me. Sorry 'bout that. Working on a fix now

**Comment by anthonynogales** [comment]
[Bad Data.txt](https://github.com/rmcrackan/Libation/files/8962998/Bad.Data.txt)

Could that be related to this error I'm getting when adding a second account?

**Comment by rmcrackan** [comment]
Issue \#2 resolved. \#1 still remains: to gracefully catch these no-longer-available pdf.s without crashing

**Comment by Mbucari** [comment]
@rmcrackan Re Bad Data in RSA parameters, that _shoud_ not be possible anymore.  I occasionally got that error, which is why I redesigned the key parser inside CreateRsaProviderFromPrivateKey().

@anthonynogales I would love to see your private key for that account so I can find out why this is failing.  I totally understand if you don't feel comfortable doing that, but if you do, you can email it to mbucari1@gmail.com.  I thought I had fixed this, and I've truly got no idea why it's still failing.

@rmcrackan  Re PDF downloads.  I think we should scrap `GetPdfDownloadLinkAsync` and `validatePdfDownloadUrl` and only use `GetDownloadLicenseAsync` for both audio files and pdfs.  `GetDownloadLicenseAsync` also gets the pdf url, and it has been debugged like crazy and has tons of error detection for thing like the user not having access to the files. It also retrieves the PDF url [because of the requested response groups](https://github.com/rmcrackan/AudibleApi/blob/6c562edbe173778e21c584cd1739e52a758943f3/AudibleApi/Api.Download.cs#L42).

**Comment by rmcrackan** [comment]
@Mbucari that's fine. I like the debugging stuff in `validatePdfDownloadUrl` though, so let's pull something like that into the shared api call. Those regex calls aren't bad but they also aren't negligible; make sure they only get called in a failure condition and not every time.

**Comment by Mbucari** [comment]
@anthonynogales Perfect! And since you've re-added the account successfully, that old rsa key is now invalid, so no more privacy concerns.

**Comment by rmcrackan** [comment]
> Seeing that deleting the user account from the GUI and re-adding it didn't fix the issue

If you delete *and save*, the account entry is deleted from that file. If you delete, don't close that accounts box, re-add the same one, then save -- it's not deleted/re-added. This is intentional to hedge against mistakes.

**Comment by rmcrackan** [comment]
Honestly, I'm starting to lose the plot: what pending real bugs need to be fixed in order to consider this issue resolved?

1) @rdow64 stopped responding the same time @anthonynogales got here -- are you one and the same? Or is @rdow64 's original issue still pending? If the latter: rdow64, can you re-upload the most recent log files? They somehow didn't get included here.

2) @anthonynogales was crashing due to no-longer-available pdf.s . This is where @Mbucari 's `GetDownloadLicenseAsync` idea can fix it.

Did I miss anything?

**Comment by anthonynogales** [comment]
@rmcrackan Sorry for the confusion on my part. I was seeing Libation crash due to the PDF not being available to me anymore. Later in the day I was getting a second error where the library wouldn't update books on the second account without crashing and giving me the Bad Data error.  I had _thought_ there might be something related with how something or other is reaching out to Audible to fetch data but the two issues were unrelated.

**Comment by Mbucari** [comment]
@anthonynogales Can you please still email me your old backup so I can fix the key decoding algorithm?

**Comment by anthonynogales** [comment]
@Mbucari I emailed it earlier today.

**Comment by Mbucari** [comment]
@anthonynogales Got it. It was in spam.  And thank you. I was able to find the problem and fix it.

**Comment by rmcrackan** [comment]
Awesome! Do you anticipate that the upcoming release will solve this issue?

**Comment by rmcrackan** [comment]
Thank you for your patience. See if [version 8.1.2](https://github.com/rmcrackan/Libation/releases/latest) solves your issue. If it doesn't, it should at least give us much better logs to figure this out.

**Comment by anthonynogales** [comment]
> Thank you for your patience.

No! Thank you all for all the work you do on this! I'll download 8.1.2 tonight and give it a spin.

**Comment by Mbucari** [comment]
> Do you anticipate that the upcoming release will solve this issue?

Yes, my last PR solves both of @anthonynogales errors.

The pdf error will be handled in the same way as audiobook errors are handled when a user not longer has access to the book.  ie. AudibleApi will log the reason for failure and throw an exception. That exception will be caught by the queue downloader, and the queued item will show an error state.  Then the rest of the queue will continue processing.

The other issue only ever happens when a new account is authenticated and a new private key is delivered.  If that key can't be parsed into RSA parameters, then for all practical purposes that authentication is bad and the user has to delete it and try again. After my fix, this should no longer happen.

**Comment by rmcrackan** [comment]
@Mbucari Thanks!

@anthonynogales Per Mbucari's last comment, your issues should now be fixed so I'll close this. If these same issues persist, reply here with details and it's no problem for me to re-open the case.
