### ISSUE TITLE
.cue sheets missing chapters

### ISSUE THREAD

**Issue by tormaid** [rmcrackan/Libation#304]
I recently finished backing up my collection on another computer and I realized belatedly that the .cue files Libation generated this time were missing all chapter information. Only the first line with FILE "Book Title.m4b" MP3 remained. The metadata in the .m4b files looks fine and contains the proper chapters and timecodes. I don't have "Allow Libation to fix up audiobook metadata" checked, but I didn't on the previous machine either. This was on Audible Japan and happened to all regular and plus catalog titles in my library as far as I can tell. I'm just wondering if this is a bug with Libation's generation of .cue sheets or something weird with my system. I've tried some basic troubleshooting like disabling the option to generate .cue sheets, re-starting Libration, then re-enabling it, but they still don't come out correctly. I've attached my log in case that helps.

Thank you in advance for your time.

[Log202206.log](https://github.com/rmcrackan/Libation/files/9015700/Log202206.log)

**Comment by Mbucari** [comment]
Yes, this is an error that was introduced recently.

@rmcrackan 
The problem is here: https://github.com/rmcrackan/Libation/blob/81c3dca740f0b3c1c3a96148ed22e926de53577e/Source/FileLiberator/DownloadDecryptBook.cs#L173

I'll be unable to fix it for the next several days, but there's the source of the error if you'd like to tackle it in the meantime.

**Comment by rmcrackan** [comment]
Thanks @Mbucari for finding the area. Unfortunately I don't see why that's wrong. That logic seems correct to me -- that we want to fix up when the config allows or for any mp3.

Btw -- the fact that you linked to that line and github actually embedded it in your comment is pretty sweet.

**Comment by Mbucari** [comment]
The problem is that ChapterInfo is what's used to create the cue file, but it's only built inside that if block. So if it's an m4b file and AllowLibationFixup is not checked, ChapterInfo never gets created and so the cue file will not have any chapters.

**Comment by Mbucari** [comment]
There's a couple of ways we can go about fixing this. The first way is two build the ChapterInfo from the api's metadata regardless of user settings so that it's available to build the cue file, but then only use it to change the chapter markers inside of the audio file if the user has selected AllowLibationFixup.

The second option would be to build the cue file using AaxFile.ChapterInfo. AAXClean will set that property after finishing conversion of the audio file. If you supplied AAXClean with a ChapterInfo info, AaxFile.ChapterInfo we'll be set with that same ChapterInfo. But if you called ConvertTo* with a null ChapterInfo, AaxClean will read the chapters embedded in the aax file and will set AaxFile.ChapterInfo from the embedded chapters.

I like option 1 better because, as we know, chapter info from the API is often different and usually better than what's embedded in the aax file. But option 2 is easier to pull off, just call create cue with AaxFile.ChapterInfo.

And sorry about not explaining this better last night. I was pretty drunk 😆

**Comment by rmcrackan** [comment]
Thanks. That is a much better explanation. I have no preference as to which solution. I'm not opposed to doing it but it won't be immediately. I still need a little hiatus.

I originally chose the name Libation because it just fit well with "Library" and "Liberate" but I'm also no stranger to the real deal. I still feel proud of my dad humor for naming the new debugger app "Hangover" -- for when Libation goes bad
