### ISSUE TITLE
Error while filtering

### ISSUE THREAD

**Issue by andysexton** [rmcrackan/Libation#308]
[_Log202207.log](https://github.com/rmcrackan/Libation/files/9077397/_Log202207.log)

**Comment by Mbucari** [comment]
@rmcrackan I'd love your input because I have no clue.

The offending line:
https://github.com/rmcrackan/Libation/blob/38d280b7f4e0380610fafda9cee8b0b73977ce90/Source/LibationWinForms/GridView/GridEntryBindingList.cs#L207

Presumably, [Collection.Remove()](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.collection-1.remove?view=net-6.0#system-collections-objectmodel-collection-1-remove(-0))  calls [Binding list.RemoveItem()](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.bindinglist-1.removeitem?view=net-6.0) , but if it's throwing an out of range exception, I think that means there's a .net implementation error. That seems crazy unlikely to me, so again, would love for you to weigh in on this.

**Comment by rmcrackan** [comment]
@andysexton Did this happen only once? Or more than once?

**Comment by andysexton** [comment]
I got similar errors during the install of this updated version, then the first couple of times I tried a search.

Now that I've closed out and restarted Libation after seeing it the first couple of times, search seems to be working.

Maybe it was just a setup problem. I can't recreate at the moment. I can let you know if I see it again. Maybe it was something weird with my machine.
________________________________

**Comment by rmcrackan** [comment]
Hmm, weird. If you can't reproduce it, we'll just call it a fluke. If you can, just reply here with the new log and I'll reopen the issue.
