### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by CommanderL** [rmcrackan/Libation#315]
[_Log202207.log](https://github.com/rmcrackan/Libation/files/9136156/_Log202207.log)

**Comment by rmcrackan** [comment]
Interesting error. Is the title still in your audible library?

**Comment by CommanderL** [comment]
every title is failing.

the whole list is just failing.

thanks for the prompt response

________________________________

**Comment by Mbucari** [comment]
@rmcrackan I don't know why his download are failing, but I know why we're not getting useful logs.

His https requests are throwing exceptions, but not `ApiErrorException` exceptions, so they're caught by the general exception handler here:

https://github.com/rmcrackan/AudibleApi/blob/f77626fa7c76768bba9b2b98421d2353b92e3c55/AudibleApi/Api.Download.cs#L59

It tries to create an `ApiErrorException`, and to do that it tries to create a `Uri` from `requestUri`. The problem is that `requestUri` isn't a valid uri, so the `Uri` constructor throws an `UriFormatException`

A cheap, dirty fix is to replace `new Uri(requestUri),` with `new Uri($"audible:{requestUri}")`. A better fix would be to construct the real absolute uri that was called when the error happened. something like:
```C#
new Uri(((SealedHttpClient)Client).BaseAddress, requestUri)
```
But that's more casting and assumptions inside an error handler, and could potentially lead us right back here where our exception handler throws an exception.

**Comment by Mbucari** [comment]
@CommanderL were you using libation before version 8.2? If so, were you having these problems with previous versions?

**Comment by CommanderL** [comment]
it has happened on every version of the program I have downloaded

Only learnt of the program yesterday

**Comment by rmcrackan** [comment]
@Mbucari Thanks!

@CommanderL Sorry about this! Like Mbucari said: I'm not sure the issue, but I just added some better logging to that area. Please try [version 8.2.3](https://github.com/rmcrackan/Libation/releases/latest) and share the new log.

**Comment by CommanderL** [comment]
oh I forgot to send an email saying its working now
________________________________

**Comment by rmcrackan** [comment]
That's great news! Thanks for the update

**Comment by rmcrackan** [comment]
Sorry, I'm a bit lost. You created an issue 3 months ago which you said was resolved but this latest post says you just learned of the program. I assume there's some miscommunication. Regarding errors, please reply with your latest log file.

**Comment by CommanderL** [comment]
I learned of the program and a day later the issue happened.
which was when I made the ticket

it was resolved three months ago and I have not made any posts since then.

________________________________

**Comment by rmcrackan** [comment]
Thanks. I just got this, supposedly from you 6 hours ago.

> only learnt of the program yesterday  so used the version that was out then
> and then the updated version that came out a couple of hours back
> 
> had the same errors on both

I also got a lot of other odd notifications today/last night. I think there must have been a bug in the github notifications. Sorry for the confusion.
