### ISSUE TITLE
no library content recognized

### ISSUE THREAD

**Issue by lobsterbake** [rmcrackan/Libation#323]
Account login appears to succeed, but import fails to find any items (should find 70 or so).

Thanks!
[Log202207.log](https://github.com/rmcrackan/Libation/files/9184896/Log202207.log)

**Comment by lobsterbake** [comment]
forgot to mention that this is with a Japan account

**Comment by Mbucari** [comment]
You're getting "Website Temporarily Unavailable". 

Are you able to access audible.co.jp and browse the site?

**Comment by Mbucari** [comment]
@mkb79

His authenticated api requests are succeeding, but the unauthenticated api request (to /1.0/catalog) are failing. Instead of returning the requested catalog content, it's returning an html page saying "Website Temporarily Unavailable"

I remember seeing this exact webpage when I was making malformed requests to the amazon /user/profile endpoint.  The website was not actually down, it was just tellng me it was instead of telling me that I was making a bad request.

If the same thing is happening now with the catalog endpoint, then maybe audibe has changed their api again and the catalog endpoint is no longer reachable in japan if unauthenticated?

**Comment by lobsterbake** [comment]
Hello. Yes, I am able to access and browse audible.co.jp.

I also have an update. 

I left the Libation interface open for a couple of hours and came back to my computer to find that the library had populated. So, at some point over a span of two hours or so (with no changes on my end), the issue seems to have at least temporarily resolved itself. I have attached an updated log file, in case it is helpful to you (it looks like the first 'success' may be in the reflected in the neighborhood of line 481?).

[Log202207.log](https://github.com/rmcrackan/Libation/files/9185520/Log202207.log)

**Comment by rmcrackan** [comment]
Sorry for the headache. I'm so glad it fixed itself.
