### ISSUE TITLE
Possible bug in chardonnay Books path

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#334]
Per [conversation on reddit](https://www.reddit.com/r/audible/comments/w9xp8i/libation_chardonnay_v83_linux_beta/ii8bl01/)

User tries to set a custom books path `foo/bar` but books are getting saved in `foo/bar/Books`. In Classic, this would save to `foo/bar`

At first glance, is this the culprit?

https://github.com/rmcrackan/Libation/blob/master/Source/LibationAvalonia/Dialogs/SettingsDialog.axaml#L69-L72

(I tried to do the nifty embedded code line but I don't think I'm doing it right.)

While we're at it, this should be expanded with OS and also classic/chardonnay/winforms/avalonia/whatever. We do it for Libation.exe vs LibationCLI.exe but that doesn't help with Chardonnay since they're both called Libation.exe

https://github.com/rmcrackan/Libation/blob/master/Source/AppScaffolding/LibationScaffolding.cs#L280

**Comment by Mbucari** [comment]
I fixed the books Dubdirectory thing.  I was trying to copy your DirectoryOrCustomSelectControl logic, but I guess I messed it up.  The SubDirectory is only supposed to be added to KnownDirectories, not custom ones, right?

I also added ReleaseIdentifier to logging, but not I'm not sure that's a good idea.

What do we actually need/want to know about the user's execution environment?

We want to distinguish between the CLI and GUI, great, that's taken care of with the assembly name.

We want to know if the GUI is win-classic, win-chardonnay, linux-chardonnay, or mac-chardonnay: great, taken care of in my code by adding the ReleaseIdentifier to logging startup.

But what about CLI-win, CLI-Linux, CLI-mac?  We probably should distinguish between those. The problem is, how?

In GUI-classic it's easy because we set ReleaseIdentifier from LibationWinForms, which is only released as part of win-classic. In the GUI-chardonnay we can distinguish between windows and unix using `Environment.OSVersion.Platform`

But in the CLI, we won't be able to distinguish between win-classic and win-chardonnay because they are built exactly the same.

Another unsolved problem is how to differentiate linux distros and macOS?  `Environment.OSVersion.Platform` returns `PlatformID.Unix` for both linux and mac runtimes.  I've looked and can't find a reliable way to do it.

**Comment by rmcrackan** [comment]
> I fixed the books Subdirectory thing. I was trying to copy your DirectoryOrCustomSelectControl logic, but I guess I messed it up. The SubDirectory is only supposed to be added to KnownDirectories, not custom ones, right?

Muchas gracias. That sounds correct

> I also added ReleaseIdentifier to logging, but not I'm not sure that's a good idea.

Why not? It's just an enum. Edit: ah, I see below: chardonnay doesn't use this enum 

> What do we actually need/want to know about the user's execution environment?

OS and classic vs avalonia

> We want to distinguish between the CLI and GUI, great, that's taken care of with the assembly name.

Yup

> We want to know if the GUI is win-classic, win-chardonnay, linux-chardonnay, or mac-chardonnay: great, taken care of in my code by adding the ReleaseIdentifier to logging startup.

That works. It'd be nice to have a more clear way to know right then that we're running chardonnay but what you said makes sense.

> But what about CLI-win, CLI-Linux, CLI-mac? We probably should distinguish between those. The problem is, how?

We already have Libation vs LibationCLI. We just need the OS. Dinah.Core has some OS identifying in Go.To which can help

> But in the CLI, we won't be able to distinguish between win-classic and win-chardonnay because they are built exactly the same.

Non-issue. If they're running the CLI it doesn't matter what it was packaged with. They don't interact so it's irrelevant which Libation.exe happens to be in the same dir.

**Comment by Mbucari** [comment]
Perfect. With your above confirmations my pending PR is correct.

**Comment by rmcrackan** [comment]
Fixed in [v8.3.2](https://github.com/rmcrackan/Libation/releases/latest)
