### ISSUE TITLE
Screen Reader Compatibility with chardonnay  windows version

### ISSUE THREAD

**Issue by douglangley** [rmcrackan/Libation#335]
**Describe the bug**
The windows chardonnay  build does not support screen readers.

**To Reproduce**

go to 
http://nvaccess.org and download the NVDA screen reader and run it.
open the libation chardonnay  build.

try and tab through the interface  and all you hear is silence.
OCR is showing the welcome screen but you can't interact with it via the keyboard or hear speech feedback from NVDA

**Expected behavior**
You should be able to get to all portions of the app with the keyboard and get spoken feedback throughout the application.
You can also test and see how the NVDA Screen Reader works with the classic build.

**Screenshots**
**Platform**

windows 10.

**Comment by rmcrackan** [comment]
Is this true for Windows Chardonnay only? Or does this issue also happen with the original (Windows Classic)?

**Comment by douglangley** [comment]
The classic version is usable with a screen reader. Its only broken with the chardonnay  build.
There are a lot of blind people that use libation, so I figured it was better to log it early on.

**Comment by Mbucari** [comment]
@rmcrackan 
It looks like accessibility is just unsupported in avalonia. I found some talk of porting WPF accessibility into avalonia for windows at least, but it doesn't look like anybody has even started the work yet. This might be a reason to keep classic alive longer than you would like.

**Comment by rmcrackan** [comment]
Yeah. My research showed the same.

So infuriating. One of the most requested things ever and no one can figure it out: a good .net cross platform front end library. Winforms is windows only. I don't remember the issue with wpf but it was lacking. Maui, even once it does come out fully, won't do linux. Avalonia doens't support accessibility... And meanwhile there is absolutely no more requested feature. Calling it now: Maui is going to be stillborn just like microsoft's last few attempts (universal, silverlight, ...) because decades later they still aren't serious about what people need. /rant

I'm going to close this issue. Not because it isn't important -- it very much is. But there's nothing we can do about it. Looks like there is no exit path for classic. This is a scenario I very much did not want but we really have no choice.

**Comment by Simon818** [comment]
I hope this doesn't reopen the issue. Someone told me about this project today, and I'm just commenting to say that I appreciate your willingness to keep the classic version alive, as someone who would be pretty much screwed without it. I recognize that this is basically the only way forward and not a super great option development wise, but a lot of people, given the same situation, would just leave legacy builds available but stop updating them when it became impractical. I will follow this thread and do what I can to support the project.

**Comment by rmcrackan** [comment]
@Simon818 Thank you for your support. My daughter was born with a disability and through her I am tied in to lots of disability communities. None of them are related to sight, however it's made me keenly aware of accessibility in general and what life looks like without it.

Over time, Chardonnay will definitely get better accessibility. It's a much newer project and the tech it's built on continues to improve year after year.

There are a few major reasons why I have no intention to abandon Classic in the near-term, if ever. It's built with tech which is boring and creates UIs which looked out of date 15 years ago. But it's also rock solid, mature, and has great support for less sexy features; like accessibility.

btw -- this thread will stay closed
