### ISSUE TITLE
New bug?

### ISSUE THREAD

**Issue by GladsGhost** [rmcrackan/Libation#341]
This error popped up on 8.2.5 so I updated to 8.3.6 and got the same thing
[Log202208.log](https://github.com/rmcrackan/Libation/files/9254632/Log202208.log)
.

**Comment by rmcrackan** [comment]
Does this still happen if you create an `Images` folder on your G drive?

**Comment by rmcrackan** [comment]
My gut says this is probably a permissions issue blocking Libation from creating folders on that drive. If you run Libation as admin it might help uncover if that's the issue

**Comment by GladsGhost** [comment]
G is just external flash. I did not get any notifications from Windows that
something was denied access. There is an images folder on it, but nothing
in there is dated later than April 21st, which was several versions and
backups ago.

**Comment by GladsGhost** [comment]
I just tried to run as admin and got identical error.

**Comment by rmcrackan** [comment]
Approx. what was the last version that worked for you?

**Comment by GladsGhost** [comment]
8.2.5 worked on July 23.

**Comment by GladsGhost** [comment]
I just did a clean install of 8.3.6 classic on a different computer. Works,
except I can't figure out how to exclude the podcasts so it's showing 1341
"visible books" as not downloaded:^) I liberated my three new purchases
since last week so just have to figure out how to ignore 900+ podcast
episodes, and to tell it that the 400 other titles have already been
downloaded. I'm using the same flash drive which I have designated as the
download location but it's not recognizing what's already on there as
liberated.

My assumption is that if I delete what's on the other machine and start
again with a clean install that it will work without getting that error
message.

Cheers, and thanks.

**Comment by GladsGhost** [comment]
P.S. figured out the podcast thing.

**Comment by rmcrackan** [comment]
I'm admittedly a bit lost now. Sounds like you got some stuff working but not everything. What remains?

Details about liberated status: when you download a book, the liberated status is set to 'downloaded' -- this status is stored in the database.

If you move the book's files, the database still remembers it as downloaded. This means you can do whatever you want with your files and Libation doesn't think 'it's gone -- better download it again.'

You can also manually change a book's status. If you want to re-download a book, manually set it's status to 'not downloaded' and you can download it again. Or if there's some podcast you don't ever want to download, you can manually set its episodes to 'downloaded' to trick Libation into not doing so.

One last thing: since this is stored in the database, if it was downloaded from another computer or if an old database was downloaded, then the new database has no way of knowing that.

**Comment by rmcrackan** [comment]
This thread appears to have stalled out and it's not obvious if any issues remain so I'm going to close it. If you're still having trouble relating to this issue, you can reply and I'll be happy to re-open it.

**Comment by GladsGhost** [comment]
Haha, you're not nearly as lost as I am. Computer A was what the log file
came from when it failed. It was working on July 23 with 8.2.5. I tried
that today, it failed, I updated to 8.3.6, it failed again. That's the log
file I sent.  I gave up and went to Computer B (both are Win 10), deleted
older version and installed 8.3.6. That worked but it didn't recognize
anything as liberated because it was a different machine. I have all the
files on external drive which was plugged in and named as destination. I
have over 400 titles. Is there a way I can manually tell it to mark
everything as liberated as a bulk operation without having to go title by
title?

**Comment by rmcrackan** [comment]
Yep! I made a feature for exactly this case. (Ok, not *exactly* but close.) The "Visible Books" menu will let you set all books to "downloaded".

More specifically, that menu has a few bulk actions which it can apply to everything in the grid. For no search, that means every book in your library. Or you can use the search/filter box to be more surgical. For instance I have a `halloween` tag that will show me all of my creepy stuff. To ensure all my Stephen King books are included, I search `"Stephen King"` (with quotes) \> Visible Books \> Replace Tags \> `halloween`
