### ISSUE TITLE
"Object reference not set" prevents download of audiobooks

### ISSUE THREAD

**Issue by gazeto** [rmcrackan/Libation#368]
Audiobook (tried 2 different ones) purchased in Audible as per usual. I can download the AAX from the Audible web interface without issue. But when trying to liberate I receive the following error(s):

> 8 Sep 22 22:37	Download & Decrypt Step, Begin: [000829237X] Lifespan: Why We Age – and Why We Don’t Have To
> 8 Sep 22 22:37	Download & Decrypt Step, Completed: [000829237X] Lifespan: Why We Age – and Why We Don’t Have To
> 8 Sep 22 22:37	Download Pdf Step, Begin: [000829237X] Lifespan: Why We Age – and Why We Don’t Have To
> 8 Sep 22 22:37	Download Pdf Step, Completed: [000829237X] Lifespan: Why We Age – and Why We Don’t Have To
> 8 Sep 22 22:37	Error downloading PDF. See log for details. Error summary: Object reference not set to an instance of an object.
> 8 Sep 22 22:37	Download & Decrypt
> 8 Sep 22 22:37	ERROR. All books have not been processed. Most recent book: processing failed
> 8 Sep 22 22:37	ERROR: Object reference not set to an instance of an object.

Libation Chardonnay 8.4.4.1 and 8.1.7.1 (same issue) on a Windows 10 **without admin rights!**
Full log attached: [Log202209.log](https://github.com/rmcrackan/Libation/files/9531935/Log202209.log)

**Comment by rmcrackan** [comment]
Very strange. It seems like it can't find your accounts file but that doesn't make sense since you were able to use it to import your library. Let's completely delete this account credentials from Libation and re-add them. (Don't worry -- **no** books or audio files are affected. You will have to log-in again though.) Then try to download and see if you get the same error.

Go to:

* Settings
* Accounts
* delete your account(s)
* Click Save
* re-add your account(s)
* try again to download

**Comment by gazeto** [comment]
Thanks for your answer!
I had tried this before and deleted + re-added my account, to no avail.

**However**, what simply helped right now is to **remove the two titles from the library** and them have them added again by doing an account scan. Everything worked well from thereon.

So: Issue resolved!
