### ISSUE TITLE
JSON export missing part of title

### ISSUE THREAD

**Issue by wtanksleyjr** [rmcrackan/Libation#37]
I found an interesting bit of corrupt data in `B00CURDK9Y` (`Empires and Barbarians�� The Fall of Rome and the Birth of Europe`). I pasted that in from the tag itself as reported by mutagen, I can see two unknown characters, presumably bad UTF.

The interesting thing is that in the JSON export, the title cuts off with a single trailing space, so the subtitle is completely missing. Usually subtitle and title are colon-separated, but in this case there's that corrupt character in all of the title data.

https://www.audible.com/pd/Empires-and-Barbarians-Audiobook/B00CURDK9Y

**Comment by Mbucari** [comment]
The Fall of Rome and the Birth of Europe is a subtitle, and the export doesn't (yet) export subtitles.

It is a Unicode character. Here's the mutagen readout:
`Empires and Barbarians\xa0: The Fall of Rome and the Birth of Europe (Unabridged)`

So I think @rmcrackan said he'd add subtitles to exports. As for the metadata tag itself, I'm inclined to leave them as-is instead of stripping data.

**Comment by rmcrackan** [comment]
> I think @rmcrackan said he'd add subtitles to exports.

I do not remember rmcrackan saying this :)

I'm all for it if you'd like to give it a go. It seems likely that subtitles are already in a api/json field. Then it's just a matter of sticking it into the Book entity during library => db import

**Comment by rmcrackan** [comment]
Closing this issue. Fixed in code. Will be included in next release
