### ISSUE TITLE
Download Podcast in Single folder

### ISSUE THREAD

**Issue by Kumarashantanu** [rmcrackan/Libation#381]
There are podcast ( Audible Original Podcast) which is around 20-25 episodes,Yes I can download them. But issue is each episode is saved under different folder, not single folder. Each episode make it's own folder.
So it is possible to make them to downlaod in single folder. So file management will be easy.

**Comment by rmcrackan** [comment]
Definitely possible. Custom file naming can help you here. Go to Settings and click on the "Download/Decrypt" tab. In "Custom file naming" there are 3 custom naming rules --  the one lets you customize what folder to save to. Edit it and put this at the beginning of that naming format: `<series>\`

If you want to re-download those titles after you make this edit (so that they re-save to folders), change the books back to 'not downloaded'. You can do this one title at a time with the row's right-side "Tags and Details" button. To do this in bulk, you can do a search so you only see the books you want to change. Then use the "Visible Books" menu to change all of them back to 'not downloaded'. A new "liberate" will now re-download them.

**Comment by Kumarashantanu** [comment]
You liberated me from my problem, Thank you

**Comment by rmcrackan** [comment]
lol You're quite welcome
