### ISSUE TITLE
Safe to upgrade older version/reinstall/run?

### ISSUE THREAD

**Issue by SpongebobSquamirez** [rmcrackan/Libation#385]
I'm on version somewhere between 5.4.9 and 6.3.2. I've been too afraid to launch it and upgrade b/c of all the bugfixes that seemed to happen right after some big release, making me unsure of when it was really going to be stable; so I don't remember whether I ran some of the newer versions in that version range or if I just downloaded them to have on my device; but recent releases sound pretty stable based on the notes now, so I want to upgrade to 8.5 classic (windows 10).

If I just run Libation.exe from the 8.5 folder, is there much risk of having any problems with my library, depending on what my current version is? If so, is there a good way you can recommend to check which version my computer is currently using first?

**Comment by rmcrackan** [comment]
There have been a lot of changes since then. Recent versions of Libation will show you the version at Settings \> About. If yours is too old for that, go to the folder with Libation.exe in it. Find the file `AppScaffolding.dll`, right click \> Properties \> Details tab \> version

You might be fine to run the latest version as-is. To be safe though, I'd run every major version between what you have now and the current one. So if you're on version 5-dot-whatever, download 6. Run Libation and make sure your library looks right. Then do the same for 7, 8, and the latest 8.5. Ignore any upgrade prompts. Other than download time, this shouldn't take very long.

If you're really paranoid, you can backup your settings files too but this shouldn't be necessary. All of those files are in the folder with your logs. You can skip backing up the Images folder. It's often large and it doesn't need to be backed up.

* [v6.0.1](https://github.com/rmcrackan/Libation/releases/tag/v6.0.1)
* [v7](https://github.com/rmcrackan/Libation/releases/tag/v7.0.0)
* [v8](https://github.com/rmcrackan/Libation/releases/tag/v8.0.0)
* Latest: [v8.5](https://github.com/rmcrackan/Libation/releases/tag/v8.5.0)
