### ISSUE TITLE
Linux beta

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#390]
The original Libation is Windows only. We recently did a massive rewrite of the whole UI to make it cross platform. I need linux people to tell me if it works for them. I know nothing about using linux. I wouldn't even know if my output file was correct.

**Comment by rmcrackan** [comment]
[From reddit](https://www.reddit.com/r/audible/comments/w9xp8i/libation_chardonnay_v83_linux_beta/ivqpl7r/?context=3):

I installed the Linux version, 8.5.1 on Ubuntu 22.04 today and here is my experience.

Installation would be way nicer with a

* deb package
* or even better a PPA from where updates would be downloaded automatically

Lowercase letters are more Linux-ish:

* sudo mv /usr/bin/Libation /usr/bin/libation
* sudo mv /usr/bin/Hangover /usr/bin/hangover
* sudo rm /usr/bin/LibationCli

Other users could not access the application:

* sudo chmod 755 /usr/lib/libation/Libation
* sudo chmod 755 /usr/lib/libation/LibationCli
* sudo chmod 755 /usr/lib/libation/Hangover
* sudo chmod 777 /usr/lib/libation

Removed unnecessary permissions for the icon:

* sudo chmod 644 /usr/share/icons/hicolor/scalable/apps/libation.svg

App start icon didn't show up:

* I modified /usr/share/applications/Libation.desktop so the Exec points to /usr/bin/libation

App threw an error (visible in terminal) upon first start:

* sudo touch /usr/lib/libation/appsettings.json
* sudo chmod 666 /usr/lib/libation/appsettings.json
* this file contains a path to /home/someuser/Libation, therefore if more users use it on the same computer it won't work properly
* this should be located in ~/.libation

So this was the installation. Felt like I went back in time a decade. And it took me a few good hours to figure it all out as this was the first time I installed this application.

Afterwards the application worked nicely. Added the account and login went smoothly (user/pass than 2FA, all in tiny windows, way better than opening up a browser window).

What I don't like is that the application does not care about my system UI settings. Letters are tiny, thin and the whole interface is super bright. I am a dark theme user whenever possible. I can live with it as I need to use it 2x each month.

Download and liberation went fast and smooth. I really appreciate the chapters in the m4b files contain the proper chapter titles, I could not do that when using ffmpeg to convert aax to m4b.

But with two books the liberation failed due to the filename being too long. The m4b file was sitting in a tmp folder, and it was impossible to copy to the Books folder until I renamed it to a much shorter name. The application should only use the title in the filename and skip the subtitle - those are sometimes ridiculously long.

* found it in the settings and changed all <title> to <title short>. This should be the default

This is really a beta version on Linux, it works, but it needs a power user currently.

**Comment by mverboom** [comment]
I've used multiple versions (8.5.1.1) currently.

After initially setting up for my own user, it actually worked and I could download my books, which was GREAT :+1: 
I tried to convert it into a system install (so out of my homedirectory), but that runs into the problem with the appsettings.json that the application wants to write into its installation path (which is now not owned by the user). So I gave up on that (after trying to fool it with an ld preload library). It would be great if the appsettings.json would be read from the users homedirectory, or if that is too specific a change for only the linux version, that it would be a commandline option that could specify the location?

Downloading works fine, but I did have to spend a lot of time getting the filename formatting in line. I think it filters filenames with : in them because of driveletter references in windows? No such problem on linux, and I use the : in my other book names. But not a big problem to work around.

So although it is not point and shoot, I am VERY happy with having a Linux version of an audible app!

Regards,

Mark

**Comment by rmcrackan** [comment]
@mverboom oh crap, is a colon a valid linux filepath character?

**Comment by wtanksleyjr** [comment]
Yes, ":" is valid in Unix in general ... so's almost everything (except
slashes and NUL I think), although please nobody write tabs or newlines
into filenames ;) .

-Wm

**Comment by adams141** [comment]
why are the linux releases full of exe and dll files, and no install-libation.sh ?

**Comment by Mbucari** [comment]
@rmcrackan I have a fix for xplat characters replacement. I'll make a PR either tonight or tomorrow, depending on how lazy I feel.

**Comment by morpheus092511** [comment]
im very new to Linux is there a deb file of this available

**Comment by rmcrackan** [comment]
@morpheus092511 Not yet. This is one of the things [I hope someone will be able to help with soon](https://github.com/rmcrackan/Libation/issues/410#issuecomment-1358113555).

Anyone here happen to know how to create a deb file?

**Comment by wrampy** [comment]
@rmcrackan I have been using Ubuntu for over a decade, I can have a look into its inner workings and how debs are actually created. PPAs and snaps are another option for installing applications. I'll get back to you in a few hours to let you know if I am actually able to do it after doing some research.

**Comment by wrampy** [comment]
Here is the first version of a script that converts the .tar.gz Linux binary file to .deb that can be installed with a single command. The uploaded file was renamed from .sh to .txt as GitHub doesn't allow uploading of script files.
[targz2deb.txt](https://github.com/rmcrackan/Libation/files/10320497/targz2deb.txt)

**Script description**
* it creates the necessary folder structure
* it creates a preinstall script to remove the old version of Libation (if installed)
* it creates a postinstall script to set up links and workarounds
* it creates a control file that is the main part of a .deb file
* extracts the .tar.gz
* copies the .desktop and .svg files to the proper location in the folder structure
* creates the deb file
* deletes the folder structure (not needed anymore)

The pre and post-install scripts are based on the "install-libation.sh" script used so far.

**Script usage**
1. download the .tar.gz file
2. download the script and rename to .sh
3. move both files to an empty directory
4. add execution permission to the script file (chmod +x)
5. run the script (no need for sudo), with one parameter the filename of the .tar.gz
```
$ ls
Libation.8.7.0-linux-chardonnay.tar.gz  targz2deb.sh

$ chmod +x targz2deb.sh

$ ./targz2deb.sh Libation.8.7.0-linux-chardonnay.tar.gz 
Working dir: Libation.8.7.0-linux-chardonnay
Exec dir: Libation.8.7.0-linux-chardonnay/usr/lib/libation
Icon dir: Libation.8.7.0-linux-chardonnay/usr/share/icons/hicolor/scalable/apps/
Desktop dir: Libation.8.7.0-linux-chardonnay/usr/share/applications
Debian dir: Libation.8.7.0-linux-chardonnay/DEBIAN
Extracting Libation.8.7.0-linux-chardonnay.tar.gz to Libation.8.7.0-linux-chardonnay/usr/lib/libation...
Copying icon...
Copying desktop file...
Creating pre-install file...
Creating post-install file...
Creating control file...
Changing permissions for pre- and post-install files...
Creating .deb file...
dpkg-deb: building package 'libation' in 'Libation.8.7.0-linux-chardonnay.deb'.
Done!

$ ls
Libation.8.7.0-linux-chardonnay.deb  Libation.8.7.0-linux-chardonnay.tar.gz  targz2deb.sh
```
If all goes well you should see what is above.

**To install Libation from .deb**
```
$ sudo apt install ./Libation.8.7.0-linux-chardonnay.deb
```
It may also install `ffmpeg` if missing.

**To uninstall Libation (after .deb install):**
```
$ sudo apt remove libation
```
This won't delete the /usr/lib/libation folder because we created the "appsettings.json" file afterwards. Note to developers: this file should not be stored in "/usr/lib/libation", but instead under "/home/username/.libation".

**Comment by rmcrackan** [comment]
Wow, thanks!! Before I add this to the documentation, can any other of you fine linux folks give this a try and see if it works for you also?

**Comment by morpheus092511** [comment]
> Wow, thanks!! Before I add this to the documentation, can any other of you fine linux folks give this a try and see if it works for you also?

I'll give it a try this afternoon

**Comment by Mbucari** [comment]
@wrampy Brilliant!

@pixil98 Do you think you can add wrampy's script to the build workflow?

**Comment by cadric** [comment]
sorry if this is wrong place to ask, but I see multiply request for a .deb for install.
But what really would help me and many others was if if there was a flatpak ( https://www.flatpak.org/ )
With that the program would work across most linux distros and would run in a container. Hope this is something that could be considered for the future.

**Comment by Mbucari** [comment]
@cadric There's now a docker image of Libation on dockerhub. Is that good enough for you?

**Comment by wtanksleyjr** [comment]
I don't know if it would work for him, but I would propose some changes to
make it work for me.

Specifically, right now it's bundled in a .sh file and with a configuration
that so far as I can tell cannot be overridden -- it will run every 30
minutes with a config that I can't figure how to override. I would suggest
that a general-purpose docker file should at least have an option to run
only on demand (I can write my own script to run it periodically).

I'd also like some clarity on how to properly configure it. I'm absolutely
puzzled what file I'm supposed to put where. I know I'm supposed to map
/config to a folder containing the settings file, but when I run it I get
an error message that tells me it's not looking in /config but instead
/libation -- and the filename it's looking for isn't the same as the name
in Windows. I don't have any access to /libation, so I don't know what to
do. I posted a bug report for this, but I don't know if I got something
wrong on it. Or rather, I KNOW I did, but there's no documentation so I
don't know what's wrong.

-Wm

**Comment by wtanksleyjr** [comment]
I've run the DEB creation and installed the result. It seems to work
plausibly, I just have to figure out where I need to put all of the
settings files :) .

**Comment by rmcrackan** [comment]
@wtanksleyjr Pretty soon Libation v9 will be released and the 'beta' threads will be closed. Since this is a specific concern about docker and DEB, can you create a new ticket for it so it won't get lost?

I'm tagging @Mbucari , @pixil98 so they can keep an eye on this too. Let me know if I've missed anyone.

**Comment by wtanksleyjr** [comment]
Update: got everything working through the DEB. Yay!

I don't see how to combine episodes into a single podcast folder, was that
proposed feature ever implemented?

**Comment by wtanksleyjr** [comment]
Feel free to ignore my Docker complaints here; I gave up on Docker, I just
cannot approach it and don't have enough knowledge to debug it -- I'd be
happy to resume once some documentation gets written so I can guess what I
SHOULD do instead of working in the dark and seeing everything fail in the
same way no matter what I do.

The DEB package works for me, so I'm very happy with that.

-Wm

**Comment by Mbucari** [comment]
>  I don't see how to combine episodes into a single podcast folder

Go to Settings \> Download/Decrypt \> "How to Format the folders in which files will be saved" \> Edit

Edit the folder naming template to something like this:

`<first author>\<if series-><series>\<-if series><title>`

**Comment by Danation** [comment]
Chiming in with some positive feedback to say the app itself works great for me on Linux (Kubuntu 22.04 specifically).  Thanks for this!

Installation was a bit of a struggle, but I see that it's a known issue and knowledgeable Linux folks are helping to improve the process.

**Comment by rmcrackan** [comment]
Starting in version 9, moving macOS and Linux from beta to full support. I'm closing the beta threads now and new issues can be opened individually as they arise. Thank you *so much* for helping beta test Libation!!
