### ISSUE TITLE
Won't decrypt.

### ISSUE THREAD

**Issue by Audible1** [rmcrackan/Libation#402]
Libation has been working fine until the last couple of weeks (before the 8.5.1.1 upgrade) With the old app as well as the upgrade i keep getting the same set of messages for every book:
<HTML>
<BODY>
<TABLE><TR><TD>12/4/2022 3:41:12 PM</TD><TD>Download &amp; Decrypt Step, Begin: [1799914526] Lord Foul’s Bane: The Chronicles of Thomas Covenant the Unbeliever, Book 1</TD></TR><TR><TD>12/4/2022 3:41:13 PM</TD><TD>Download &amp; Decrypt Step, Completed: [1799914526] Lord Foul’s Bane: The Chronicles of Thomas Covenant the Unbeliever, Book 1</TD></TR><TR><TD>12/4/2022 3:41:13 PM</TD><TD>Download &amp; Decrypt: &nbsp;Decrypt failed</TD></TR><TR><TD>12/4/2022 3:41:13 PM</TD><TD>ERROR. All books have not been processed. Most recent book: processing failed</TD></TR></TABLE>

</BODY>
</HTML>
This is consistent now, nothing will decrypt, all my new books show a yellow light.

![image](https://user-images.githubusercontent.com/119823420/205526623-e81d3a07-cd2a-4bb4-bff4-daad2708f766.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
Windows 10
[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libat
[Log202212.log](https://github.com/rmcrackan/Libation/files/10149905/Log202212.log)
ion log file here.

**Comment by rmcrackan** [comment]
The errors make it look like you don't have access to these books.

* Is this the correct US audible account? e...k@c...x.n...t
* Maybe delete the account, save, then re-add the account. It will prompt you again for your password

Let me know if this helps.

**Comment by Audible1** [comment]
It is the correct account, we only have the one account.  I am able to download “in original format”.  It’s the decrypt to MP3 that seems to be the hang-up.  On a slightly different topic, now that I have downloaded several as m4b with chaptering, is there a way to go back and re-download as M4b all the ones I original downloaded as MP3 (before this current glitch)?

 

Thanks for the help,


Ed

**Comment by rmcrackan** [comment]
@Mbucari : to me these look like an account issue but OP says it's an mp3 thing. Thoughts?

@Audible1 : in the right hand column there's a button for tags and details. In there you can re-set the book to not downloaded. Then you can change the decrypt/download settings and do it again. You can also set the downloaded status in bulk in the Visible Books menu at the top.

**Comment by Mbucari** [comment]
Sorry, I'm just seeing this now.

For some reason, AAXClean.Codec's built-in aac decoder library (ffmpegaac.dll) is not being found.

@Audible1 
ffmpegaac.dll should be in the Libation program files directory. Do you see it in there?

**Comment by Mbucari** [comment]
@Audible1

OK, I was able to recreate this error.  The your problem is that you copied a fresh copy Libation to 'C:\Program Files (x86)\Libation'.

The ffmpegaac.dll is stored as an embedded resource and is extracted/copied to the Libation folder when it's needed. The error arrises because 'C:\Program Files (x86)\' is write protected, so ffmpegaac.dll cannot be extracted.

As a workaround:
- Move 'C:\Program Files (x86)\Libation' to another location on your computer that has write access.
- Run Libation and download any book as an mp3. This will create the ffmpegaac.dll in the Libation folder.
- Move Libation back to 'C:\Program Files (x86)\Libation'

@rmcrackan 
Storing that lib as a resource is (obviously) not a good idea, but at the time I did it I couldn't figure out how to add other assets to the nuget package. Since then I think I have figure it out, so I'll change AAXClean.Codecs to do it correctly.

However, this is not the only error that can happen when Libation is run from $programfiles%. If you try to put a fresh copy of Libation in %programfiles%, it will throw an error trying to create appsettings.json. It also won't be able to update because the updater isn't run with admin privileges. Maybe add a disclaimer that Libation must have write access to its own program files directory?

**Comment by rmcrackan** [comment]
@Mbucari Good idea. [Done](https://github.com/rmcrackan/Libation/blob/master/Documentation/GettingStarted.md#installation)

I could have appsettings.json be more flexible. Like, if you can't write there then try to create in the Users folder. 1: that wouldn't solve the auto-updater issue. 2: the edge cases quickly get weird when there are multiple potential sources of truth

**Comment by Mbucari** [comment]
In the .NET Framework days I'd use the built-in configuration manager, and those .config files were stored in %localappdata%. I like the idea of storing basing settings files like appsettings.json in `Environment.SpecialFolder.LocalApplicationData`. That folder is well-defined and writable on Windows, macOS, and Linux systems.

As for the updater, I checked and it actually is run with admin on windows systems, so that should not be a problem.

**Comment by rmcrackan** [comment]
@Audible1 Please follow Mbucari's instructions to solve.

@Mbucari Ok, I'll bite: how does Libation not running as admin have permissions to run the updater running as admin??

**Comment by Mbucari** [comment]
> how does Libation not running as admin have permissions to run the updater running as admin??

You start a new process with the "runas" verb. The user is prompted to approve running the process through UAC.

**Comment by rmcrackan** [comment]
Damn, I forgot that I have UAC turned off. I wonder if all users have to click 'accept' or similar to upgrade

**Comment by Mbucari** [comment]
> I wonder if all users have to click 'accept' or similar to upgrade

I'm sure most do. Few people turn UAC completely off (I used to in Win7, but I think it's a lot less of a pita now that it was back then).
