### ISSUE TITLE
Add option to store folders as author last name

### ISSUE THREAD

**Issue by lycannon** [rmcrackan/Libation#420]
Please add a tag on the Download/Decrypt settings to store files by author's last name then first name separated by a comma (e.g. Lastname, Firstname)?

**Comment by rmcrackan** [comment]
Unfortunately, this one's probably not going to happen. The typical case is dead simple: "Arthur Conan Doyle" becomes "Doyle, Arthur Conan". If only they were all so simple. What about when there are multiple authors? I guess I'll pick whichever audible happens to list first. Often though this is the person doing the forward, not the real author, so that's not great. Then there are issues like hyphenated names. There's no easy way to tell a real name like Heitor Villa-Lobos vs audible's sloppy labelling like Stephen King-Introduction.

**Comment by lycannon** [comment]
Somehow, it doesn't surprise me that the Audible API's don't give great metadata- I was hoping that it would return authors in an easy to consume format and list narrator and forward person as separate entries; of course it they did, I'm sure you'd have already added the option.

Since Audible and Amazon are the same, you might have success pulling from the Amazon API like Calibre does- but that's might be a lot of work for a convenience feature.

**Comment by rmcrackan** [comment]
The amazon api won't help here because audible ruined the 'name' field by cramming extra metadata in there like the previous examples, or "Bob Smith translator". The amount of metadata in names is the big blocker. Years ago I tried to collect all the metadata words that could be added to names; there's no standard though so that was a fool's errand.

Other fun issues which are annoying but not necessarily blockers:

* parentheses with metadata
* no author listed
* last names where the space is part of the last name: Vincent Van Gogh, Verner von Braun, Leonardo da Vinci
* incorrectly formatted honorifics. If it's `Ken Smith Jr` instead of `Ken Smith, Jr.`, then the last name will be `Jr`. Even worse when you have multiples like MD, PhD
* inconsistent initials: A.B. Jones, A. B. Jones, AB Jones
* a minor "author" being listed first. The minor author most often happens for intros where they list that one first presumably because the intro occurs first, or putting a big name first to increase visibility: `Stephen King-contributor, Joe Nobody`
* publisher including their name in the authors and sometimes it's first and sometimes it's last. So you can have `Bob Jones, The Great Courses` and `The Great Courses, Bob Jones`

The sum effect is: I'm not up for name parsing. It gets too ugly.

**Comment by rmcrackan** [comment]
FYI, this is getting some additional scrutiny. Watch #481 for progress.
