### ISSUE TITLE
How to recreate folder structure?

### ISSUE THREAD

**Issue by linguax-gc** [rmcrackan/Libation#426]
Hi, I don't know if there is a way to do this implemented already. If not, please, take this as a suggestion.

I would like to recreate the folder structure of my downloaded books without having to redownload everything. For example, I have the standard folder structure, but I want to change it to <first author> - <title short>. Is there a way for the program to do this automatically ?

Thank you very much for your awesome work! And happy holidays!

**Comment by rmcrackan** [comment]
A few more details are in #414 . Progress for both will be tracked here.

**Comment by AshbyGeek** [comment]
I'm going to copy some comments from issue 600 that relate to this issue

**Comment by AshbyGeek** [comment]
> > #426
> 
> I really would like to make that feature, but it's fraught. If you begin remaining and suddenly one of the files has the same path/name as another file, what do you do? Give it a temp name until you that other file is renamed, the go back and rename it? That can get _very_ hard to juggle correctly.
> 
> Maybe create a temporary books folder and move/rename all files into it, then move all files back to the main books folder? Maybe, but then you're running into potential problems like:
> 
> * If the temp books directory is a sub directory of the primary, then file path lengths may be too long
> * If the temp books directory is a sibling of primary, they it may not even be on the same physical machine if the user is using symbolic links.
> 
> And then we have the problem of file locks. This is only a problem on Windows, but services like the search indexer and cloud folder sync may lock some files and prevent renaming/moving. Then what? Just leave the mess for the user to clean up?

**Comment by AshbyGeek** [comment]
From @rmcrackan 
> RE https://github.com/rmcrackan/Libation/issues/426 -- I love this in theory. In practice, it's filled with all the problems you mention and so many more. Bulk file management is a logistical minefield.

**Comment by AshbyGeek** [comment]
From @CharlieRussel

Re: 426. Don't go there. Applications that try to manage the file system on Windows are doomed to problems and sorrow. BTDT, got the t-shirt.

**Comment by AshbyGeek** [comment]
I understand that file management is a bit of a pain, but all the issues that have been mentioned:
* file path lengths
* physical machine location
* file name collisions
* file locks
already need to be accounted for during the download process. Could we refactor that code so that it can be used both during download and during library re-organization? Build a switch into it so that it will either download the file or copy it from another file/location?

**Comment by Mbucari** [comment]
> already need to be accounted for during the download process.

Most of them don't. File path lengths is probably the only one from your list that we really need to worry about when writing new files.

Physical machine location is taken care of by the user when they select their download folder. All Libation knows is that's a good place to write files. Anywhere outside of that is undiscovered country, and **let's through file system permissions into the mix**. Libation may not have access to any other parts of the file system. Maybe the temp folder? But that very likely could be on a different hard disk in which case the move would be glacially slow.

File name collisions for new downloads are handled by appending " (n)" to the filename. It's fine if you're adding a new copy of something, but it's wrong if the collision would have been resolved once that second file had been renamed. So again we're back to tracking collisions and fixing them at the end.

When you're writing a new file, there's nothing to lock. Libation creates the file, write it, then closes it. After that, anything can happen.

What happens if Libation crashes or there's a power outage? Can the renaming be resumed if interrupted? Probably if it was designed to be, but it's more complicated. And the file that was being moved at the time of abort, has it been corrupted? No way to know unless we has before and after the move (but only if we're physically moving files as in the temp folder situation described above).

<hr>

That's enough about system/environment problems. Let's move on to data problems.

There only way Libation can identify a file is if its filename contains the Audible Product ID (`<id>`), or if the file is in Libations FileLocations.json. `<id>` is included in every naming template by default, but users can change that. FileLocations.json can get corrupted automatically reset. So then what? Just ignore them and leave a mishmash or directory structures and filenames?

Then we've got split audiobooks. How do we detect the chapter order? The only reliable way would be to open each file read its metadata.

What do we do with unknown file types? Some media players create additional files next to the audio file. Do we assume they belong to the book that's in that folder? What if there are multiple books in that folder (because, for instance, the user decided to group all books by author), but the new naming template specifies that books are split into their own folder?
<hr>

This is one of those problems that's easy to get to 90%, hard work to get to 98%, and virtually impossible to get to 100%. And unlike the author name parsing problem, I think this one needs to be 100%.

This is the most I've thought about this request since it's been posted, and the more I think about it the more I don't want to attempt it.

**Comment by rmcrackan** [comment]
[You're off the edge of the map...](https://www.youtube.com/watch?v=dm4bkJFiLJw&t=64s)

**Comment by AshbyGeek** [comment]
Haha, ok.

**Comment by Mbucari** [comment]
Sorry everyone, this just isn't going to happen.

**Comment by rmcrackan** [comment]
Mbucari has the authority to make this call on his own. Just to be clear though: I endorse his decision.
