### ISSUE TITLE
Undo Remove from library

### ISSUE THREAD

**Issue by Allylleal** [rmcrackan/Libation#433]
I looked through through the documentation and couldn't find the steps for this. I accidentally hit 'Remove from library' instead of Locate File while right clicking the Liberate icon on a book. 
I've already tried to rescan, remove and then add my account and then rescan. Is there a quick fix I'm missing?
It was too easy to remove the book from the library if it's permanent.

**Comment by Mbucari** [comment]
Launch the `Hangover` app. It's a recovery program in Libation's folder.

**Comment by Mbucari** [comment]
@Allylleal were you able to undelete your books?

**Comment by imno007** [comment]
This does not work for me. The deleted titles show back up in Libation, but when I click to download them, I get a "File not found" error.

This has been an issue for a couple of versions now, including the latest. I probably encounter it more than most because I often convert in both lossless format and by chapter, but I can no longer do this in Libation because I can't import the books a second time. It's usually not a problem, because I'll just convert once as lossless with Libation and then chapterize in Inaudible, but occasionally Inaudible will for some reason hang on converting a Libation .m4b conversion.

**Comment by imno007** [comment]
[_Log202301.log](https://github.com/rmcrackan/Libation/files/10385571/_Log202301.log)

**Comment by Mbucari** [comment]
@imno007 I only see one book download attempt in your log file (Sherlock Holmes: The Thinking Engine), and it was successful.

Can you try downloading one of the problem books again then post that log file? (Also, I think the log files with a preceding underscore are backups. Pick the one without the underscore).

**Comment by imno007** [comment]
I think you're misunderstanding, which might be down to me. Yes, I could download it, but once I remove it from Libation, I cannot download it a second time. 

Also, the reason you only see one download, and why the log being a backup probably does not matter in this case, is because I uninstalled Libation, all folders, and reinstalled it.

**Comment by rmcrackan** [comment]
What happens if you RIGHT click on the stop light and click 'set download status to not downloaded'. Then LEFT click.

Does that start a new download?

**Comment by imno007** [comment]
Yes, THAT works - thank you! Sorry, I somehow managed never to see that option.

And sorry for the long delays in responding. As it happens, I suddenly find that Inaudible is no longer working for me to convert .aax files (even with keys installed), so I was trying to troubleshoot that at the same time. ;)

**Comment by rmcrackan** [comment]
You're welcome. You can also set this status from the top 'visible books' menu. It will apply your desired status to *all* books in the grid.

Good luck with inaudible. It's time has probably passed. It was an amazing tool in its day -- I actually used a reverse engineered version of it for proto-Libation. Audible has changed it's encryption a lot and inaudible hasn't been updated in over 6 years.

**Comment by imno007** [comment]
That's good to know! Thank you, that will save me some time from now on.

You're probably right about Inaudible. It was working fine for me until a week or so ago, although I've mainly just been using it to chapterize the M4B files I downloaded with Libation, but suddenly it won't convert .aax at all - and apparently, for some reason, not even the M4B files. It used to have trouble with one once in a while, as I mentioned above, but I tried more of them today and for some reason it wouldn't chapterize any of them to MP3 (although it still works with the older ones I have). And this is the case on two computers I have it installed on. I know that Amazon made changes to their DRM for ebooks a few days ago (had to buy an old Kindle just to get around that), so maybe they sneaked some other changes in there. Who knows.

Anyway, thanks again - and keep up the good work! I really appreciate this program and your constant improvements. :)

**Comment by Mbucari** [comment]
When you say chapterize, what do you mean?

**Comment by imno007** [comment]
Just exactly what Libation does if you choose the split-to-chapters option. As I mentioned above, I was only using Inaudible for that because I wasn't able to download the titles a second time. In Libation, I used to download the first copy as lossless, then remove it, and import it again to download and divide by chapter into MP3's, but at some point the second import stopped working, and as you know, I never managed to stumble on the other options. But yeah, I won't need to go outside Libation any more for that, so I'm okay if Inaudible has finally bitten the dust.

**Comment by Mbucari** [comment]
@imno007 Good. I Just wanted to make sure you were availing yourself of all audio file options in Libation  :)

**Comment by imno007** [comment]
Right, thank you. The only thing missing is an option to download an m4b version _and_ to split to MP3 chapters at the same time. Not complaining - I'm not even sure how feasible it is! - but that's why I do it like that.

**Comment by rmcrackan** [comment]
Now available in [version 9.4.3](https://github.com/rmcrackan/Libation/releases/latest). Settings\> Trash Bin
