### ISSUE TITLE
Auto Upload to Audiobookshelf

### ISSUE THREAD

**Issue by kucksdorfs** [rmcrackan/Libation#445]
Would it be possible to use the Audiobookshelf API to automatically upload liberated books? They have a fairly extensive API that allows for uploading files and indexing based on the asin index. The relevant API endpoints are linked below.

I can see having a textbox for the URL, if that detects ABS then prompt for credentials and then a Library to upload to and after a book is liberated upload and then match.

https://api.audiobookshelf.org/#login
https://api.audiobookshelf.org/#upload-files
https://api.audiobookshelf.org/#match-a-library-item

**Comment by kucksdorfs** [comment]
My apologies, I accidently hit shift+enter or ctrl+enter before completing the description.

**Comment by kucksdorfs** [comment]
Thank you for the quick reply. Is there any chance the export functionality could include the file path if it is downloaded? I can create another issue but won't bother if that isn't functionality that you want included.

**Comment by rmcrackan** [comment]
> Is there any chance the export functionality could include the file path if it is downloaded?

Sorry, I'm not clear on what you mean. Example?

**Comment by Gatewayy** [comment]
I use Audiobookshelf and Libation. I just configured ABS to use my
Libation folder for my audio book  library in ABS and every time a book
is added to that folder watch picks it up and adds it into the ABS Web
GUI.  With that being said, I do not think this type of integration is
actually needed? :)

On January 11, 2023, flysalad ***@***.***> wrote:
> Thank you for the quick reply. Is there any chance the export
> functionality could include the file path if it is downloaded? I can
> create another issue but won't bother if that isn't functionality that
> you want included.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/rmcrackan/Libation/issues/445#issuecomment-
1378914111>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ACYMXP3KJLK7W2JCKGI2JYLWR3EXZANCNFSM6AAAAAATYECG3Q>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>

**Comment by kucksdorfs** [comment]
@rmcrackan Is it possible to include the location on disk in the file export? You have information like the Account, Title, and BookStatus, could another column be added for the location on disk

(E:\Audible\Your First Listen\Your First Listen\Your First Listen [B002V8N37Q].m4b would be the location of the Your First Listen on my PC).

**Comment by kucksdorfs** [comment]
@Gatewayy Would you mind sharing your Custom File Naming folders/files? I am not opposed to making ABS share a folder with Libation, but last time I tried (a few months ago to be honest) I couldn't get the naming convention working correctly (authors and series were very messed up - if books happened to be in the correct series they weren't in order).

**Comment by rmcrackan** [comment]
@kucksdorfs Ah, now I get it. Thanks.

A founding principle is to give the user access to all their books, DRM-free, then let them do anything they want with them. To that end, Libation generally does not make an effort to track where files live.

On a practical level, this is also difficult because of how many people 'chapterize' their books. This results in multiple files per book, one or all of which could be moved.

**Comment by wtanksleyjr** [comment]
Hold on, let me check my scripts, I think I have something for this that
isn't TOO specific to my setup...

**Comment by wtanksleyjr** [comment]
[loadmeta.py.txt](https://github.com/rmcrackan/Libation/files/10394201/loadmeta.py.txt)

OK, so this script scans a given folder for m4b files that contain an ASIN (AudibleProductId) that's contained in the given json file. When it finds such an m4b file, it creates a yaml file containing the metadata from that ASIN in the original JSON.

I can make a minor change so that I instead create a OPF file containing only the ASIN and a custom genre like 'LibationCreated', which would make it easy for you to grab all of those imports and run a Match on them.

**Comment by wtanksleyjr** [comment]
... loading an ASIN from an OPF is a brand-new feature in the latest version of Audiobookshelf, so I wasn't able to do it before.

**Comment by wtanksleyjr** [comment]
OK, the attached script tests out well for me.

You need to have two folders to keep all your metadata backed up; one has to be your Libation Book folder (where all your m4b files get downloaded to, I assume m4b for now) and the other should just be whereever's convenient for you; it'll contain deduplicated backup copy of all metadata this script ever reads, I use it because I have multiple audible accounts and don't want to risk overwriting all of my metadata if I reinstall Libation.

Before you run this, you'll need to configure Libation to save m4b and include the ASIN in the filename (that's the default, so if you didn't change the config it'll work); run `libationcli scan`, `libationcli export -p ~/Libation/Books/books.json -j` (replace that folder name with your own choice), and `libation liberate`. (Of course the GUI works too, but the CLI's way quicker.)

Now, run `./loadmeta.py ~/Libation/Books ~/au/sources/downloads/Audible/`, replacing those folder names with your own choices.

So first, it loads both the backup and the new `books.json` files, and then it'll write all of the new metadata into the backup file. (It loads the backup file so I can fall back on it in case the folder being scanned has an ASIN that's in the backup but not in the new metadata; I've been doing this a long time and ran into this one or two times.)

It'll then scan the first folder, and every time it finds an m4b file it'll search its filename for an ASIN (Audible ID) that's known to it. When it finds one, it'll drop a file `book.json` containing the book's metadata (in case you need it later) and a `metadata.opf` for AudioBookShelf.

I personally recommend configuring AudioBookShelf to prefer OPF files; I also recommend _not_ configuring Libation's folder to download into ABS's folder; I like to have a script move the folders once I scan them. That's not included with this, though; right now my folder move script is too specific to my setup.

I also add a fake Genre tag `Autoloaded & Needs Manual Matching`. This reveals one weakness; the reason I need this is that apart from manual matching AudioBookShelf makes it very hard to import books that belong to multiple series, so I don't even try.

Anyhow, here you go.

[loadmeta.py.txt](https://github.com/rmcrackan/Libation/files/10406836/loadmeta.py.txt)
