### ISSUE TITLE
error installing on debain bullseye

### ISSUE THREAD

**Issue by LynchMicro** [rmcrackan/Libation#463]
**Describe the bug**
Install throws an error message regarding unknown compression

**To Reproduce**

wget -O libation.deb https://github.com/rmcrackan/Libation/releases/download/v9.1.0/Libation.9.1.0-linux-chardonnay.deb && sudo apt install ./libation.deb

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libation' instead of './libation.deb'
The following NEW packages will be installed:
  libation
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/76.5 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 /home/***/libation.deb libation all 9.1.0 [76.5 MB]
dpkg-deb: error: archive '/home/***/libation.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive /home/***/libation.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 /home/***/libation.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Expected behavior**
Install libation.

**Screenshots**

See terminal text copied above

**Platform**
Debian GNU/Linux 11 (bullseye)

**Log Files**
n/a

**Comment by Asselberghs** [comment]
From what I am reading your system fails to install the Debian package because it dosn't know the zst or Zstandard compression, which granted I didn't either before I searched for it.
To me it looks like you could follow this guide for example:
https://www.maketecheasier.com/compress-files-with-zstd-linux/
Installing zstd giving your system the package it needs to handle that compression form, and run it again, then it should know of that compression and proceed with installation.
Since you are on Debian more concretely then:

sudo apt install zstd

And try again, the link is a little more in dept, I just copied out what I believe is the important part.
Rmcrackan & Mbucari probably have a better solution, I am just hoping I might be able to help you debug your terminal output.

**Comment by LynchMicro** [comment]
Thanks. Installed zstd but getting same error. I wonder if it is related to this - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664

If so I guess I need to wait until dpkg (1.21.18) comes to bullseye (I have dpkg 1.20.12)

**Comment by Mbucari** [comment]
@LynchMicro try this:

1. Download the [targz2deb.sh](https://github.com/rmcrackan/Libation/blob/master/Scripts/targz2deb.sh)
2. Change line number 131 to the following:
`dpkg-deb -Zxz --build $FOLDER_MAIN`
3. Download the latest Libation tar.gz and build the Deb like so
`sudo ./targz2deb.sh ./Libation.9.1.0-linux-chardonnay.tar.gz 9.1.0`
4. Try installing the deb

**Comment by LynchMicro** [comment]
@Mbucari The package you linked to in the edit worked (I didn't try the first method). Thank you

**Comment by rmcrackan** [comment]
Fixed in [latest](https://github.com/rmcrackan/Libation/releases/latest)
