### ISSUE TITLE
after installing latest update, unable to open folder with existing books [from email]

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#483]
This was sent to my personal email. Put here for visibility, triage, and tracking:

I noticed the following issue two updates ago.  
After installing the update, I click on the green button in the Liberate column.  I get the "File not found" error message instead of having the explorer open to the location of the book.  
No paths were changed and the install directory remained the same. The update was performed from the automatic prompt.

I would appreciate any insight you can provide.

**Comment by Mbucari** [comment]
The first obvious question is if this is an ongoing problem them, or if something changed once and made his whole FileLocations.json useless. I noticed a couple of releases ago that FileLocations was broken because I had added a second constructor to `LongPath and didn't mark one of them as a `[JsonConstructor]`. This caused the json parser to throw an exception which caused Libation to delete the existing FileLocations.json and make a new one.

**Comment by Andytr1** [comment]
Original reporter - Just got source code and stepping through. It appears that the regex generated with productId is not matching anything. 
It's happening in BackgroundFileSystem.cs_FindFiles()::44. This only happens for books that were liberated before the patch. Any books that were imported after update are working fine.
I wonder if the fsCache is not being populated correctly.

**Comment by Mbucari** [comment]
@Andytr1 Can you please email your `FileLocations.json` file to me mbucari1@gmail.com. When you do, can you also give me one example of a book that is found and one example of a book that isn't found?

**Comment by Andytr1** [comment]
You are right. Looks like FileLocations.json gets deleted/re-created. I am looking at it and it only has the books liberated after upgrade and a lot of other books are missing from it.
Is there a way to regenerate it?

**Comment by Mbucari** [comment]
@Andytr1 If your audio files of the folder contain those files has the audible product ID in the name (e.g. \[B00DJ8JAY2\]), Libation should find them. If you didn't use the \<id\> naming template, I believe you're out of luck.

@rmcrackan please correct me if I'm wrong.

**Comment by Andytr1** [comment]
I didn't use the option of having product ID in the name. I guess I will manually have to find a way to crawl the database/audio book files to recreate the FileLocations.json.

**Comment by Mbucari** [comment]
> I didn't use the option of having product ID in the name. I guess I will manually have to find a way to crawl the database/audio book files to recreate the FileLocations.json.

If your bandwidth is uncapped, the path of least resistance might be to just re-download them. I'm sorry for the error :/

**Comment by Andytr1** [comment]
I decrypt to m4b. What are pros/cons of either ?

**Comment by Mbucari** [comment]
> m4b. What are pros/cons of either ?

M4b is by far superior. Unless you have a specific need for an mp3, I would always recommend m4b.

The reason I ask is because the m4bs contained the audible product ID in metadata, so those tags can be read to recreate your library. That functionality doesn't exist in libation yet, but I could probably whip up a standalone tool really quickly.

**Comment by rmcrackan** [comment]
> If your audio files of the folder contain those files has the audible product ID in the name (e.g. [B00DJ8JAY2]), Libation should find them. If you didn't use the <id> naming template, I believe you're out of luck.

This is correct.

**Comment by rmcrackan** [comment]
The fix is [here](https://github.com/rmcrackan/Libation/pull/487#issuecomment-1426613423). Available in [latest](https://github.com/rmcrackan/Libation/releases/latest)
