### ISSUE TITLE
Docker .net7 research

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#491]
Dockerize .NET Applications without Dockerfile. Built-In Container Support for .NET 7:

[Containerize a .NET app with dotnet publish](https://learn.microsoft.com/en-us/dotnet/core/docker/publish-as-container)

@pixil98 @wtanksleyjr @Mbucari -- anyone have experience or opinions on this?

**Comment by pixil98** [comment]
It looks like this is designed for long running web services where you'd have multiple background threads (Workers) that need to be coordinated. It doesn't feel like a good fit for this project to me, since this is a single foreground process and we're not handling incoming requests. I could see it working well if having a hosted service that continually checked for new books and/or provided an API for getting metadata about liberated books is a direction you'd like to go in. There might be some neat opportunities to leverage that when using software like Plex to serve the books.

**Comment by wtanksleyjr** [comment]
Actually, a plug-and-play combo of Libation and Audiobookshelf.org would be
pretty sweet.

-Wm

**Comment by rmcrackan** [comment]
Thanks! Sounds like we're not yet ready for such
