### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by manalive** [rmcrackan/Libation#497]
The Darkest Mode.

Please.

**Comment by Mbucari** [comment]
@rmcrackan

This has out of the box support in avalonia preview 5. I haven't upgraded to that yet because there are a lot of breaking changes between preview 4 and 5, and I was getting frustrated trying to migrate so I stopped. Right now preview 4 seem to be very stable, so I'm content not to migrate it until RC1 which should be the next release.

**Comment by rmcrackan** [comment]
@Mbucari works for me. I've looked into theming in winforms (which is essentially what this would have to be in that tech). The simple case is very easy. It quickly spirals in complexity. I'm not interested in adding theming and/or dark mode to classic. If you aren't either, then the answer here is: we can add dark mode to Chardonnay once Avalonia 5 is stable enough to upgrade to. Right?

**Comment by Mbucari** [comment]
> If you aren't either

I'm not

> we can add dark mode to Chardonnay

That's my thought. I want to wait for v11-RC1 to be released (which will probably be in the next 1-2 months), the migrate to it. At that point we can do theming. From what I've seen, it really is as simple as changing "Light" to "Dark" in xaml for the static case. Not sure how you make it dynamic, though.

**Comment by Mbucari** [comment]
I adjusted the colors

![image](https://user-images.githubusercontent.com/37587114/227271608-49c623e5-4baa-41c7-a658-56df035e62e5.png)

**Comment by rmcrackan** [comment]
This will be included in the next version release :)
