### ISSUE TITLE
Can not import library.. No books found 

### ISSUE THREAD

**Issue by IJKMan** [rmcrackan/Libation#5]
Looking forward to using Liberation! Installed 3.1.8, Logged in no problem. When I scan library, "takes a few minutes",  does not find a single book.. then get "Error importing library. Please try again..."

Have a complex Audible relationship, both UK and US accounts under same email and also been subscriber since 2000, so have a massive library.  Tried with both US and UK setting.. same issue.  Not sure where to find log to send to you. 

Would appreciated your help! I have been looking for a utility like yours for, well, years!

**Comment by rmcrackan** [comment]
Thanks for giving Libation a chance. I PM's you my email on reddit. Please email me your log and I'll take a look.

**Comment by IJKMan** [comment]
Thanks.. but my Reddit is IJKManUK! Can you please resend :)
Thanks

**Comment by rmcrackan** [comment]
Thank you for the log. I found and fixed the issue. Try the new version -- https://github.com/rmcrackan/Libation/releases/tag/v3.1.9

Summary: the library details were downloading just fine from your account. After the library details have finished downloading, Libation digs through all of that data and turn it into something usable for display and to facilitate downloads and decryption. It was in this post-get-library stage where the bug was occurring.

If issues persist, let me know via github or email and I'll take another look.

Thanks again!
