### ISSUE TITLE
libation bug

### ISSUE THREAD

**Issue by tmborn** [rmcrackan/Libation#507]
**Describe the bug**
Cannot log in to Audible Australia

[Log202302_002.log](https://github.com/rmcrackan/Libation/files/10812935/Log202302_002.log)
[Log202302_003.log](https://github.com/rmcrackan/Libation/files/10812936/Log202302_003.log)
[Log202302_004.log](https://github.com/rmcrackan/Libation/files/10812937/Log202302_004.log)
[Log202302_005.log](https://github.com/rmcrackan/Libation/files/10812938/Log202302_005.log)
[Log202302_006.log](https://github.com/rmcrackan/Libation/files/10812939/Log202302_006.log)

[Log202301.log](https://github.com/rmcrackan/Libation/files/10812942/Log202301.log)
[Log202301_001.log](https://github.com/rmcrackan/Libation/files/10812943/Log202301_001.log)
[Log202302.log](https://github.com/rmcrackan/Libation/files/10812944/Log202302.log)
[Log202302_001.log](https://github.com/rmcrackan/Libation/files/10812945/Log202302_001.log)
[Log202302_002.log](https://github.com/rmcrackan/Libation/files/10812946/Log202302_002.log)
[Log202302_003.log](https://github.com/rmcrackan/Libation/files/10812947/Log202302_003.log)
[Log202302_004.log](https://github.com/rmcrackan/Libation/files/10812948/Log202302_004.log)
[Log202302_005.log](https://github.com/rmcrackan/Libation/files/10812949/Log202302_005.log)
[Log202302_006.log](https://github.com/rmcrackan/Libation/files/10812950/Log202302_006.log)
[_Log202301.log](https://github.com/rmcrackan/Libation/files/10812954/_Log202301.log)

**Comment by rmcrackan** [comment]
Sorry the Australia region isn't working for you. On the password screen, there's a link that says "Or click here" which leads you through an alternate way of logging in. Can you please try that and let me know the result?

**Comment by tmborn** [comment]
Working perfectly! Thanks a lot for helping!

**Comment by rmcrackan** [comment]
Hooray! Thanks for the follow up :)

**Comment by Mbucari** [comment]
@rmcrackan have you tried using the AudibleApi username and password login method recently? I have, and I could not get it to work. It would load the first login page but would fail on redirect.

**Comment by rmcrackan** [comment]
@Mbucari Confirmed, it's not working for me today either. I don't know when I'll next be available for fixing it so at least there's the 'or click here' method.

**Comment by Mbucari** [comment]
@rmcrackan I was looking into it a couple of weeks ago. I was using [Audible](https://github.com/mkb79/Audible) as a reference (because it works as always), and I updated all string constants  (some of the strings like version numbers in AudibleApi are older than what the python package are using). It still didn't work. Then I stepped through every line of the login process in both Audible and AudibleApi, which is when I noticed that after [makeRequestAsync](https://github.com/rmcrackan/AudibleApi/blob/2119be0e4221771f83f9f890f05b04c3ccb50365/AudibleApi/Authentication/LoginResultRunner.cs#L98) redirects, the requested page is not found. That's when I gave up because I just could not see any difference between your implementation and mkb79's.
