### ISSUE TITLE
Way to create subfolders?

### ISSUE THREAD

**Issue by richardtheb** [rmcrackan/Libation#512]
**Is your feature request related to a problem? Please describe.**
I would like a way to create subfolders when liberating/backing up downloads

**Describe the solution you'd like**
I like to have things in an author folder, then a subfolder for each book. There isn't a way to do that at present (Or I can't find it if there is). So it would create a structure such as "Frank Herbert/The Ascension Factor/The Ascenscion Factor.mp3", Frank Herbert/Dune/Dune.mp3", etc.

**Comment by rmcrackan** [comment]
Yup! We have extensive support for what we call [naming templates](https://github.com/rmcrackan/Libation/blob/master/Documentation/NamingTemplates.md). This will let you create very exact file names and folder structures. They can take a bit of getting used to but they are quite versatile.

In Settings, go to the Download/Decrypt tab. There are 3 spots for templates: the folder to save books into (including sub folders), filename, and filename when splitting books into 1 file per chapter. This last one is a bit special since it might include things like chapter number.
