### ISSUE TITLE
Audiobooks.com accounts available?

### ISSUE THREAD

**Issue by fbk37** [rmcrackan/Libation#520]
Is it possible to add accounts from "Audiobooks.com"? I've got some books on their I'd like to turn into m4b. Adding the audible account worked perfect for those books so I was hoping there's something similar one could do for Audiobooks.com.

Cheers

**Comment by rmcrackan** [comment]
Sorry. There no current plans to support services other than audible. Also, m4b is supported by Libation with audible titles because that's how audible serves up the files. We don't create or convert to m4b. [This thread on reddit](https://www.reddit.com/r/audiobooks/comments/k3vsls/converting_mp3_to_m4b/) has some tips for converting from mp3 to m4b.

**Comment by wtanksleyjr** [comment]
Audiobooks used to support MP3 download, but an update a year or so ago
removed that feature; there's currently no way to get your books from them,
so far as I can tell. It's probably best to think of them as not selling
you the book, only the right to listen to it.

I switched to Audible and Downpour.

-Wm

**Comment by fbk37** [comment]
Thanks! I've got an audible account as well. I guess I'll have to live with only listening to those books in their app.
