### ISSUE TITLE
Can't download titles from plus catalog

### ISSUE THREAD

**Issue by adampalli** [rmcrackan/Libation#525]
**Describe the bug**
I have an audible (IN) subscription. When I try to download any title from the plus catalog, It's all unavailable for download. While clicking on the tile, it says "This book can't be downloaded because it wasn't found during the most recent library scan". The titles are still included in the plus catalog and I'm able to play them via the audible app.
**To Reproduce**

Add any title from the plus catalog and try to download them. 

**Expected behavior**
Audiobook should be available for download. 

**Screenshots**
![image](https://user-images.githubusercontent.com/117727805/224310926-dc33ee5e-83a3-4b63-a076-454bf48d69d3.png)

**Platform**

Windows 11, Latest version of Libation (9.4.4.1)

**Log Files**
Attach your Libation log file here.

**Comment by JakobTischler** [comment]
I have the same problem with Audible.it, which doesn't use a credit system but has "included titles" which can be added to the library.

Using Libation v9.4.4.1

**Comment by baldivox** [comment]
His discussed on Reddit _(I've just discovered and am trying out Libation and it seems to be great. I do have a Newbie question - I am getting the message that a lot of books in my library are unavailable and 'This book cannot be downloaded because it wasn't found during the most recent library scan'. Is this normal? Is it because they are free or expired books etc? Thank you.), I have the same query. You asked for the log and I'm not really an IT guy but hopefully this is what you need:

SessionID=a5d5050b-c57c-4d26-8e78-47ee34286f0a.1678446211838 Timestamp=2023-03-10T11:03:31:966+0000 ThreadID=8774 Component=ngl-lib_NglAppLib ErrorID=403 Description="GetCachedNglProfile Status: NGL Profile Unavailable"
SessionID=a5d5050b-c57c-4d26-8e78-47ee34286f0a.1678446211838 Timestamp=2023-03-10T11:03:31:970+0000 ThreadID=8774 Component=ngl-lib_NUSecureProfileDao Description="GetPrefetchedSecureProfile : Prefetched ASNP not found"
SessionID=a5d5050b-c57c-4d26-8e78-47ee34286f0a.1678446211838 Timestamp=2023-03-10T11:03:31:970+0000 ThreadID=8774 Component=ngl-lib_NUSecureProfileFetcher ErrorID=SPDaoLevelStatus:11 Description="ValidateAndGetPrefetchedSP : Failed to fetch prefetched ASNP"
SessionID=a5d5050b-c57c-4d26-8e78-47ee34286f0a.1678446211838 Timestamp=2023-03-10T11:03:31:970+0000 ThreadID=8774 Component=ngl-lib_NglAppLib ErrorID=228 Description="GetPrefetchedNglProfile Status: Data Not Found : Cached NGL Profile"
SessionID=a5d5050b-c57c-4d26-8e78-47ee34286f0a.1678446211838 Timestamp=2023-03-10T11:03:32:653+0000 ThreadID=8773 Component=ngl-lib_HttpRequestDelegate Description="Received Response with status 200"
SessionID=a5d5050b-c57c-4d26-8e78-47ee34286f0a.1678446211838 Timestamp=2023-03-10T11:03:32:771+0000 ThreadID=8780 Component=ngl-lib_HttpRequestDelegate Description="Received Response with status 204"
SessionID=a5d5050b-c57c-4d26-8e78-47ee34286f0a.1678446211838 Timestamp=2023-03-10T11:03:32:771+0000 ThreadID=8780 Component=ngl-lib_HttpRequestDelegate Description="Got empty response"
SessionID=a5d5050b-c57c-4d26-8e78-47ee34286f0a.1678446211838 Timestamp=2023-03-10T11:03:32:775+0000 ThreadID=8802 Component=ngl-lib_NUSecureProfileFetcher ErrorID=COPRetrieverStatus:13 Description="GetDeviceTokenAndProfile : We have a valid access token but could not reach COPS, fill in userprofile from IMS"
SessionID=a5d5050b-c57c-4d26-8e78-47ee34286f0a.1678446211838 Timestamp=2023-03-10T11:03:32:776+0000 ThreadID=8802 Component=ngl-lib_NglAppLib ErrorID=110 Description="GetLatestNglProfile Status: Unhandled Error"
SessionID=a5d5050b-c57c-4d26-8e78-47ee34286f0a.1678446211838 Timestamp=2023-03-10T11:04:35:967+0000 ThreadID=10845 Component=ngl-lib_HttpRequestDelegate Description="Received Response with status 200"
SessionID=a5d5050b-c57c-4d26-8e78-47ee34286f0a.1678446211838 Timestamp=2023-03-10T11:23:32:136+0000 ThreadID=30636 Component=ngl-lib_HttpRequestDelegate Description="Received Response with status 200"
SessionID=a5d5050b-c57c-4d26-8e78-47ee34286f0a.1678446211838 Timestamp=2023-03-10T11:23:32:162+0000 ThreadID=30636 Component=ngl-lib_HttpRequestDelegate Description="Got empty response"

**Comment by Mbucari** [comment]
This was supposed to be a new feature that would detect books that were no longer available to download, but it looks like I got it's not working for non-us regions. I'll look into it, but for now please revert to v9.4.3.

@rmcrackan it would be really nice to have the JSONs from library scans right about now 🫤

**Comment by rmcrackan** [comment]
@Mbucari Found it. I was wrong, it's not configurable. We can just uncomment it during testing

https://github.com/rmcrackan/Libation/blob/34f56d2fd7a4ff839c1364a8d0df40813605ccf3/Source/AudibleUtilities/ApiExtended.cs#L138-L145

**Comment by rmcrackan** [comment]
The new [version 9.4.5](https://github.com/rmcrackan/Libation/releases/latest) addresses this issue. Please try again and let us know the result.

**Comment by adampalli** [comment]
> The new [version 9.4.5](https://github.com/rmcrackan/Libation/releases/latest) addresses this issue. Please try again and let us know the result.

Issue fixed! Thanks for the swift update :)

**Comment by rmcrackan** [comment]
Thank you for your patience and for following up on this issue. Cheers!
