### ISSUE TITLE
Libation crash on start after move "Libation"-directory to external drive

### ISSUE THREAD

**Issue by elvquant** [rmcrackan/Libation#542]
Libation crash on start after move "Libation"-directory to external drive

Stop Libation, after correct working
Move Libation from /Users/xyz/Libation to external drive /Volumes/Docs/Libation
Start Libation
Select Returning User
Choose new path for Libation-dir
Libation crashes

Libation crashes on any start

Move Libation-dir back to /Users/xyz and remove ~/Library/Preferences/org.libation.macos.plist
Libation crashes on any start

No way found to start Libation!

No LOG on Libation-dir
Only Apple crash log

macOS 12.6.2 (Libation lastest)

**Log Files**
No LOG on Libation-dir

**Comment by elvquant** [comment]
Possible found (after reinstall the app) the issue.

cat Libation.app/Contents/MacOS/appsettings.json 
{
  "LibationFiles": "/Volumes/Docs-1/Libation"
}

"Docs-1" a second mount, instead of "Docs".

**Comment by elvquant** [comment]
Correcting: /Application/Libation.app/Content/MacOS/appsettings
Checking: ~/Library/Preferences/org.libation.macos.plist
Checking: /Volumes/Docs/Libation/Settings.json

All are consistent, but it Crashes. I have to use a local path

**Comment by elvquant** [comment]
The whole directory should not be moved, only the Books-subdirectory can move to an other (external) drive. That works. Leaving „Libation“-Dir on place!

**Comment by Mbucari** [comment]
@elvquant I'm glad you found a solution that works for you. The crash still concerns me and I'll look into it.

**Comment by Mbucari** [comment]
@rmcrackan The problem here is that after the Libation files folder is moved, the "Books" directory in Settings.json is still pointing to the old location. `Configuration.SettingsFileIsValid` checks that `Books` exists, and returns false if it doesn't. If a user just moves their entire Libation folder, of course that folder won't exist. I'm not sure what to do about this. Maybe if Books doesn't exist at the settings path, just create it in the Libation folder and let users change it later in the settings menu?

**Comment by CharlieRussel** [comment]
@Mbucari -- perhaps prompt with a dialog? You know, something like: 
Hey, dummy, that directory doesn't exist. Would you like us to:

1.  create it? 
2. Try somewhere else?
3. Just politely crash and let you try again?

(OK, but only half kidding. Rather than creating it in some default location, I would think a dialog/prompt for a better location would be a better solution.)

**Comment by rmcrackan** [comment]
This will be included in the next version release :)
