### ISSUE TITLE
Ability to save ASIN inside mp3/mp4 tag.

### ISSUE THREAD

**Issue by filviu** [rmcrackan/Libation#557]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add support for the asin mp3/mp4 tag ? I know it's custom (I think) but both MusicBee (if setup) and audiobookshelf (by default) support it. Would make matching audiobooks a lot easier.

**Describe the solution you'd like**
Save the asin in the asin ID3 tag.

**Comment by Mbucari** [comment]
You're in luck, because it already is! In mp4 files it's stored in the `CDEK` tag (that's the original name used bu Audible in the aax file).

In mp3 files it's stored in a user defined text field named `AUDIBLE_ASIN`

**Comment by filviu** [comment]
Ah, apologies for not looking deeper. Then it's a matter of scripting something to copy the tag to the name that audiobookshelf understand. Cheers !

**Comment by wtanksleyjr** [comment]
I don't know what tag ABS uses, but I always load using OPF files, for example:

```xml
<?xml version='1.0' encoding='utf-8'?>
<package version="2.0" xmlns="http://www.idpf.org/2007/opf">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:title>Between Shifts</dc:title>
    <dc:identifier id="BookId" opf:scheme="ASIN">1977340717</dc:identifier>
  </metadata>
</package>
```

(You can of course include any elements you want in this; anything you explicitly include will override the tag data if the appropriate ABS option is set. My library actually includes everything as OPF, since I don't trust ANY tag data.)
