### ISSUE TITLE
Clicking "Convert to MP3" does not do anything

### ISSUE THREAD

**Issue by robster7674** [rmcrackan/Libation#581]
**Describe the bug**
After downloading ok, I right-clicked on the book and selected "Convert to MP3": nothing happens.

**To Reproduce**

- download a book
- right-click the book and select "Convert to MP3"

**Expected behavior**
I expect conversion to start.

**Screenshots**

**Platform**
macOS 10.15.7 (Catalina)

**Log Files**
Attach your Libation log file here.

12/04/2023 07:50	Download & Decrypt Step, Begin: [B09HSKHKTY] The Myth of Artificial Intelligence: Why Computers Can’t Think the Way We Do
12/04/2023 07:51	Download & Decrypt Step, Completed: [B09HSKHKTY] The Myth of Artificial Intelligence: Why Computers Can’t Think the Way We Do

After the above there are no more entries.

**Comment by Mbucari** [comment]
@robster7674 Inside the Libation settings folder (located in ~/Libation) is a log file. Please upload that here. Thanks!

**Comment by Mbucari** [comment]
I think I know what's happening! You didn't clear the queue after download the audiobook, so when you tried to convert to mp3 that book wasn't added to the queue because a job for that book was already added.

I'm going to close this issue, but feel free to re-open it if the problem persists.

**Comment by robster7674** [comment]
@Mbucari thanks for the explanation. I added the log file as attachment. The behavior you describe still seems like a bug to me: why would a book that has not been converted to mp3 yet, be skipped simply because it has been downloaded before?

[Log202304.log](https://github.com/rmcrackan/Libation/files/11241819/Log202304.log)

**Comment by Mbucari** [comment]
@robster7674 It's not that you can't redownload the same book. You absolutely can. It's just you can't queue the same book more than once at a time. The reason for that is because like I said, you can absolutely download the same book multiple times. If you could queue the same book multiple times, it would be far too easy to accidentally have multiple copies downloaded for the same title. It would also clutter the queue.

But I do agree it could be smarter. Right now it only checks whether the book already exists in the queue, but it should check what operations on that book have been queued and disallow duplicates of the same operation.

**Comment by robster7674** [comment]
That would be a great improvement, thanks.

**Comment by elboletaire** [comment]
May not be a bug per se, since you coded it this way, but it's a UX bug, since we as users can only think about it as a bug, because it just fails.

I'd add, a part from splitting the detection logic as you said, that at least some kind of notification should make me aware of what's happening. In this case the queue "is empty", so an error message saying "the queue has already been processed" would be helpful too.
