### ISSUE TITLE
Possible Interruption of service.  You were denied a content license for... 

### ISSUE THREAD

**Issue by newmanm1969** [rmcrackan/Libation#592]
I just started using Libation this week to download AudiblePlus files.

Initially it was working great.

The past 2 days every time I try to download an AudiblePlus file I get this message.

Is this an issue with Audible or with Libation?

Thank you.

**Comment by Mbucari** [comment]
> Is this an issue with Audible or with Libation?

Kinda both.  It's an issue with Audible because it's not granting you a license to download your books when it should be, but its also an issue with Libation because there exists some workaround to this issue that the Audible website and app use that we haven't been able to figure out for Libation.

Time is the only cure for this. You said it's been doing this for 2days, and that's usually the maximum duration of this error.

**Comment by newmanm1969** [comment]
Thanks for the explanation.

Libation was working for me again earlier today.

Unfortunately I'm getting the same error again tonight.

Hopefully it will start working again soon as Libation is excellent when it works.

**Comment by rmcrackan** [comment]
Is there a way for you to test Libation on a different network? Starbucks ... hot spot ... basically, anything other than your typical wi-fi?

**Comment by newmanm1969** [comment]
I will try tomorrow.

It's really strange because it started to work again tonight then stopped working again for a third time.

Is it possible that downloading a lot of filles causes the license to be denied?  I have been downloading a lot of files and I wonder if that triggers something for Audible.

Thanks.

**Comment by wtanksleyjr** [comment]
I'm pretty sure it's not "a lot of files" -- I just bought a preposterous
number of books in the cash sale, and nothing even  blinked for me, it all
worked.

**Comment by Mbucari** [comment]
> Is it possible that downloading a lot of filles causes the license to be denied?

Like @wtanksleyjr, I've never seen this happen. I've done many test runs where I'll re-download my entire library, requiring a few thousand license requests in a few hours, and I've never personally seen this error. I've only ever seen it in users' log files.

**Comment by newmanm1969** [comment]
Thank you both for your replies.

I guess I'm just unlucky because it still isn't working for me so far today.

I tried a different wifi network but still no luck.

I'm going to install Libation on another computer tonight to see if that makes any difference.

**Comment by flysalad** [comment]
You mentioned "Audible Plus". Does this mean you are on the no-credit-monthly plan? I was wondering if this is the issue because the rest of us are probably Premium Plus users who are buying books with credits/cash.

**Comment by rmcrackan** [comment]
@newmanm1969 Is this still an issue?

**Comment by newmanm1969** [comment]
I was actually on a free 30 day trial through Amazon Prime.  Perhaps that is why I was having issues.

**Comment by rmcrackan** [comment]
Hmm, that shouldn't have caused an issue. Is it all 'plus' titles?

**Comment by Viel0320** [comment]
I have faced the same license problem these days, and I believe that license ban will continue full 24 hours which happens after about 175 downloads with audible plus book. 

So that's not a problem with normal users but happens with greedy plus subscriber and downloaders (like me). and will end soon so thanks to amazon.

once banned, sometimes the offline license on android app will also lose, I could only play book online before regaining the license. 

I will continue subscribing the plus plan, to observe any more information.

**Comment by KeeperOfTheFort** [comment]
Hi. Just started using Liberate yesterday and have encountered the same error as OP "Possible Interruption of service. You were denied a content license for...".

I have an active Audible.co.uk subscription with 803 visible audiobooks (mix of purchased and plus catalogue). 

After successfully backing up 167 audiobooks the error hit and one by one all the remaining 636 audiobooks turned red in Process Queue with the words: "Possible Interruption of service" repeated at the foot of each.

Fired up to try again today and the same error persists. Tried logging out of account and logging back in and tried running through VPN but no joy.

Hope there is a remedy - happy to provide any further info :) Thx
