### ISSUE TITLE
Can't be opened because Apple cannot check for malicious software

### ISSUE THREAD

**Issue by wonton-digests** [rmcrackan/Libation#611]
I downloaded the Libation app, but when I try to open it I get this message:
“Libation” can’t be opened because Apple cannot check it for malicious software.

I have a Mac running OS 13.3.1

**Comment by Mbucari** [comment]
@wonton-digests are you following the Mac installation instructions?

https://github.com/rmcrackan/Libation/blob/master/Documentation/InstallOnMac.md

**Comment by kfbest** [comment]
alternately, if you right click on the app and select Open, it will let you open the app after clicking a warning. 

Note - this will likely always be a "problem" because of how Apple deals with signing certificates. In order for this to not happen, @rmcrackan or @Mbucari  would have to pay the annual ~~extortion~~ fee to be able to be a recognized developer.

**Comment by rmcrackan** [comment]
@kfbest I still haven't gotten into mobile development for similar reasons. Back when the iPhone first announced their api.s, the first thing they did was say you couldn't even put your own programs on your own phone unless you do your development on a mac AND pay them $100/year. My computer, my phone, my coding, ... their fee? This is not money I could really spare at the time and it left me with an extremely bitter taste ever since. Apple eventually loosened the reigns a bit so you could side-load your own apps onto your own phone. This turned out to be extremely complicated to set up and even when you did, it expired after only a few days. They hadn't admitted that in fact their practice was robbery, only that there should be a free way to quickly test your app on real hardware. I've had so many ideas for personal phone apps over the years and I keep coming back to feeling slimy toward that program.

**Comment by Mbucari** [comment]
@kfbest I can't. I just can't bring myself to give in to their extortion. I don't even use a mac, though I did buy one so I could debug Libation on it. That's already kind of crazy, but I'll be damned if I shell out $100 annually for the pleasure of providing software for their ecosystem.

**Comment by kfbest** [comment]
Totally agree with you. Was just explaining to others who may not be aware of the reasons why Gatekeeper will always be a problem.

**Comment by rmcrackan** [comment]
@wonton-digests Did [these instructions](
https://github.com/rmcrackan/Libation/blob/master/Documentation/InstallOnMac.md) help?

**Comment by wonton-digests** [comment]
@rmcrackan They did. Thanks!

**Comment by rmcrackan** [comment]
Awesome!
