### ISSUE TITLE
"Save all podcast episodes to parent folder" option is not compatible with conditional naming

### ISSUE THREAD

**Issue by evan** [rmcrackan/Libation#612]
I have the following folder format string:

```<if podcast->Podcasts/<first author>/<series>/<series#[3]> - <title short><-if podcast><!if podcast->Audiobooks/<first author>/<if series-><series>/<series#[2]> - <-if series><title short><-if podcast>```

If the `Save all podcast episodes in a series to the series parent folder?` option is checked, the conditionals do not work, and I get incorrect folder output. With the option unchecked, it works fine.

Incorrect:
<img width="319" alt="Incorrect" src="https://github.com/rmcrackan/Libation/assets/210/a1a0316a-3d9d-4bbd-aa81-e2e8b5ed3bc4">

Correct:
<img width="322" alt="Correct" src="https://github.com/rmcrackan/Libation/assets/210/733c01d6-df5a-4aa3-a072-d1bc58571714">

**Comment by Mbucari** [comment]
@evan I was recently thinking about this option, and I think I've decided that it is redundant with naming templates and only adds confusion. Personally I think it should be removed, but removing features is... tricky.

I would disable that option, and then add this condition to your folder naming template:

`<if podcast-><series>\<-if podcast>`

**Comment by CLHatch** [comment]
> @evan I was recently thinking about this option, and I think I've decided that it is redundant with naming templates and only adds confusion. Personally I think it should be removed, but removing features is... tricky.
> 
> I would disable that option, and then add this condition to your folder naming template:
> 
> `<if podcast-><series>\<-if podcast>`

I was confused about why we had that option myself, seeing as it could be done with the renaming patterns.  I'm currently using this naming pattern for the folders:

`<account>\<if podcast->Podcasts\<if series-><series>\<-if series>(<pub date>) - <title> [<id>] {<narrator[separator(; )]>}<-if podcast><!if podcast->AudioBooks\<author[separator(; )]>\<if series-><series>\<series#[2]> - <-if series>(<year>) - <title> [<id>] {<narrator[separator(; )]>}<-if podcast>`

**Comment by evan** [comment]
I'm ok to remove the setting.

**Comment by Mbucari** [comment]
> I was confused about why we had that option
Legacy. It was added before naming templates could distinguish between book series and podcasts. As naming templates became more powerful, that option has become more useless.

> I'm ok with removing the setting.

@rmcrackan What do you think? Removing settings is messy business.

[Relevant XKCD](https://xkcd.com/1172/)

**Comment by CLHatch** [comment]
> > I was confused about why we had that option
> 
> Legacy. It was added before naming templates could distinguish between book series and podcasts. As naming templates became more powerful, that option has become more useless.
> 
> > I'm ok with removing the setting.
> 
> @rmcrackan What do you think? Removing settings is messy business.
> 
> [Relevant XKCD](https://xkcd.com/1172/)

Ah, that makes sense.  I only recently discovered Libation, so didn't know it didn't have that functionality to begin with.

**Comment by wtanksleyjr** [comment]
I didn't know it was possible -- so I stopped doing podcasts with Audible,
because that's the only way I was interested (I listen to podcasts by
binding them as audiobooks).

So ... sigh ... although I would have used this if I'd known, I have no
current use for it.

-Wm

**Comment by rmcrackan** [comment]
I agree with everything here. It made sense at the time. It doesn't really make sense in light of the if-podcast tag. And there will *definitely* be someone who want the spacebar heating option. :)

@Mbucari

What do you think of: we only honor the `Save all podcast episodes in a series to the series parent folder?` option if `if-podcast` is not present in any template? Could this be the best of both worlds? Or did I just create the worst?

**Comment by Mbucari** [comment]
@evan @rmcrackan

I'm now back to a place where I can explore this issue more thoroughly.

First, some facts about the SavePodcastsToParentFolder.

- When Enabled, Libation creates a folder based on the Series's parent item.
  - This item is unique from all podcast episodes and has it's own Title, Rating, Description, etc.
  - This item is identified as a series, but **it is not identified as a podcast**
- All episodes of a series are placed within that folder, **following the normal rules for directory and file naming**. This means that A podcast audio file will be inside two folders: `[Series Parent Folder]/[Episode Folder]/[Episode Audio File]`
<hr>
Reflecting a bit more, I think there's room for improvement here and that SavePodcastsToParentFolder still has some value.

Some things we could change:

- Make `<if series>` evaluate true for series parents. This should probably be done and I thing would fix @evans' issue.
- When SavePodcastsToParentFolder is enabled, do not create the `[Episode Folder]` so that all episodes are stored in `[Series Parent Folder]/[Episode Audio File]`. This could have strange side effects like:
  - The folder thumbnail would be changed after every new podcast is downloaded
  - Some folder tags will not make sense, such as
    - \<bitrate\>
    - \<channels\>
    - \<series#\>

> Or did I just create the worst?

I'm afraid so lol

**Comment by wtanksleyjr** [comment]
Personally, I absolutely love the idea of storing all episodes of a podcast
into a single folder. The outline you've described is exactly what I'd want
for most of the Audible-exclusive podcasts -- consider the serial books
like Alien and so on. You're right that there are challenges, but I wonder
if those would be helped by using the ASIN for the podcast rather than the
one for each episode, and only falling back to the episode if the podcast
didn't work.

-Wm

**Comment by CharlieRussel** [comment]
I'm personally of the save to parent folder persuasion. Mostly because podcasts seem to be the most likely to have length issues.

**Comment by rmcrackan** [comment]
This is included in v10.3.3 which will be live within the 1/2 hour.
