### ISSUE TITLE
chapter titles look weird on 10.5.2

### ISSUE THREAD

**Issue by Aoife40** [rmcrackan/Libation#663]
it looks weird with the new release version doesnt looks like on audible webplayer or the app.. old version 8.8.2 is fine, is this a bugged? i havent update the program in awhile

10.5.2 https://i.imgur.com/ARB8YeT.jpg

8.8.2 https://i.imgur.com/RaoPmFi.jpg

audible webplayer https://i.imgur.com/d6Y574L.jpg

**Comment by Mbucari** [comment]
A few months back, Audible started delivering chapter data in a tree form. Instead of a flat list of chapters and timestamps (as shown in your screenshots), chapters had a _hierarchy_. They would look something like this:

```
00:00 - 00:10	Opening Credits
00:10 - 00:25	Book 1
00:25 - 00:27	|	Part 1
00:27 - 01:40	|	|	Chapter 1
01:40 - 03:20	|	|	Chapter 2
03:20 - 03:22	|	Part 2
03:22 - 05:00	|	|	Chapter 3
05:00 - 06:40	|	|	Chapter 4
06:40 - 06:42	Book 2
06:42 - 07:02	|	Part 3
07:02 - 08:20	|	|	Chapter 5
08:20 - 10:00	|	|	Chapter 6
10:00 - 10:02	|	Part 4
10:02 - 11:40	|	|	Chapter 7
11:40 - 13:20	|	|	Chapter 8
13:20 - 13:30	End Credits
```

Unfortunately, both the .cue and .m4b formats do not support tree chapters, so they need to be flattened. I made the choice to include the titles of all levels in the chapter name because that's how I like it. It lets me see exactly where I am in the book from just the chapter name.

I appreciate that my preferences aren't shared by everyone and I we can look at adding an option, but TBH I don't even know how to describe all of this in a pithy one-liner setting name.

@rmcrackan Any ideas?

**Comment by wtanksleyjr** [comment]
Oof, that's a serious display challenge. I do like the old way of trying to
flatten it (i.e. don't try to nest them), just put nested items as a single
separate item if necessary as zero-length.

One thing to consider: can you make a different version of the chapter list
in the json that can hold the original tree-structured data, so that
third-party stuff can access it?

-Wm

**Comment by Aoife40** [comment]
thanks for responding, yeah i would love a toggle switch if its not too much trouble

**Comment by Darktide764** [comment]
I think it's a little confusing tbh when you have a giant wall of text. I do understand what you mean by knowing where you are in the audiobook @Mbucari, but I feel a less text heavy approach would be better.

Examples here:

Libation rip: https://i.imgur.com/8rpiGtY.png

inAudible rip (hand chaptered): https://i.imgur.com/8As2wLd.png

The hand chaptered from AAX via inAudible allows you to know where you are in the book without a giant wall of text. I understand you likely can't implement that into Libation, just an example to show compact is better for most people.

Thanks for all your hard work.

Regards

**Comment by rmcrackan** [comment]
Added in [version 10.6](https://github.com/rmcrackan/Libation/releases/latest)
