### ISSUE TITLE
Single Button Clear Filter

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#669]
**Is your feature request related to a problem? Please describe.**
It's a minor nuisance that when I've finished with a filtered view, that I then have to delete the entire text of the filter, and then click "filter". 

**Describe the solution you'd like**
I'd like a single "clear filter and refresh back to main page" button. One click. 

**Describe alternatives you've considered**

**Additional context**
It's a minor nit, and I know that screen real estate is always precious, but it bugs me, so I figured it never hurts to ask!
Thanks for a great program!

**Comment by rmcrackan** [comment]
The technical piece is brain-dead simple. The UX is hairy. If you put Clear next to Filter, it's easy to mis-click and delete your filter. (Would that imply we need another button for 'undo'?) Same if you put Clear between the search box and the Filter button -- now your muscle memory that used to be 'tab then enter' clears it instead of searches. Also, does 'clear' or 'reset' mean to just clear the box, or clear the box and also perform that refresh search?

Possible solutions: I found [this](https://www.c-sharpcorner.com/blogs/implementing-buttontextclear-on-textbox-winforms) which adds a little x on the side like you see in smartphones. I guess having it also perform the search wouldn't be a stretch.

Another option already available to you is to create a quick filter for `*:*`. (This is a strange little quirk of Lucene, the search engine we use. Actually when you do a blank search, Libation has to substitute `*:*` behind the scenes to trick Lucene into showing its full contents.) Other benefits of this saved quick filter: when you click it, it clears the search box and also does the search in one step. Also, it's keyboard friendly. If it's your 2nd filter: Alt , F , 2 (sequential keystrokes, not held at the same time).

**Comment by Mbucari** [comment]
You can also press enter to apply a search. It's not much, but it does keep your hands on the keyboard.

**Comment by rmcrackan** [comment]
When both developers suggest alternatives, that's likely shorthand for "probably not"

**Comment by CharlieRussel** [comment]
I'll close it then. Though I admit I liked that little x.

**Comment by rmcrackan** [comment]
The solution I linked to above looks easy enough for Classic. I have no idea how hard it would be for Chardonnay.

**Comment by rmcrackan** [comment]
Added in [version 10.6](https://github.com/rmcrackan/Libation/releases/latest)
