### ISSUE TITLE
M4B ENCODING OPTIONS

### ISSUE THREAD

**Issue by OldScotsman** [rmcrackan/Libation#684]
Hello.
Thank you so much for managing my enhancement request #677 for 

[ONE SINGLE Mp3 File - with an Embedded CueSheet]

Now I realise how clever you are  😁 I was wondering, if you could find the time, to see if it would be possible to have 
“M4B ENCODING OPTIONS” 
Like the ones available for Mp3.

I reduce the bit rate from 128 Kb to 64 kb, partly because most of us can’t tell the difference when it comes to the human voice and has therefore become the norm and on the plus side, the storage space required is halved.

Thank you
OldScotsman

**Comment by CLHatch** [comment]
> Hello. Thank you so much for managing my enhancement request #677 for
> 
> [ONE SINGLE Mp3 File - with an Embedded CueSheet]
> 
> Now I realise how clever you are 😁 I was wondering, if you could find the time, to see if it would be possible to have “M4B ENCODING OPTIONS” Like the ones available for Mp3.
> 
> I reduce the bit rate from 128 Kb to 64 kb, partly because most of us can’t tell the difference when it comes to the human voice and has therefore become the norm and on the plus side, the storage space required is halved.
> 
> Thank you OldScotsman

I likely wouldn't use it myself, because I like to try to keep files as "original" as possible, but I know many will also drop out one of the two audio tracks.  Because apparently most audiobooks that are in "stereo" actually just have duplicated left and right audio channels.

**Comment by rmcrackan** [comment]
Is this the same as #648 ? It's in Settings \> Audio File Options tab \> Audio quality to request from Audible

**Comment by OldScotsman** [comment]
It maybe but I got lost with all the technical stuff.  😁

**Comment by Mbucari** [comment]
@CLHatch @OldScotsman 

Libation doesn't "encode" the m4b files, so we can't offer any options. We can make changes to the m4b metadata, but changes to the actual audio data is a not something we do and I'm not interested in adding that feature.

Unfortunately, you can't just remove a single audio channel. Both channels are encoded together in a single audio packet. However, I don't believe there is much overhead for the duplicated channel stereo.  Because half the data is an exact copy of the other half, smart encoders should be able represent that duplicated half with almost no extra data.

**Comment by wtanksleyjr** [comment]
To be fair, what he's actually asking for is not changes to the current m4b
path (we can't change that, because it's actually the "save audio
in Audible's  native format"), but rather more output types than mp3
(including converted m4b output).

There are 2 ways to get what he wants...

One is for us to allow people to choose lower-quality download, which of
course saves disk space and download time without adding any program
complexity (it does add options complexity, and I would HATE to ever find
I'd accidentally turned the option on).

Another is to use a 3rd party audio converter, which of course would allow
converting an m4b to any desired format.

-Wm

**Comment by rmcrackan** [comment]
> One is for us to allow people to choose lower-quality download

Agreed. That's the option is available at: Settings > Audio File Options tab > Audio quality to request from Audible. You can choose high or normal. This is comparable to the official phone app:

Profile \> Settings \> Data & storage \> Download Quality: Standard or High

**Comment by CharlieRussel** [comment]
Personally, I can't imagine setting the download to Normal/Standard. "Disk" space is cheap, even SSD space is cheap. I can downgrade a high quality source to a more space sparing lower quality for use on a small portable device that has limited storage, but I can't upgrade a low quality to high.

As for converting across multiple formats -- I'm sure there are other options out there, but I long ago paid for dbPowerAmp and it can convert pretty much anything into anything else - FAST.
