### ISSUE TITLE
[Feature Request] Include evaluated file path as a column in main grid

### ISSUE THREAD

**Issue by mattalexx** [rmcrackan/Libation#700]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To assist in creating templates for directory and file naming, being able to preview the file save path of each library title would be helpful. 

**Describe alternatives you've considered**
It might be cool if a "Target save path" (bad name) column was available as a column in the main grid.

**Additional context**

**Comment by Mbucari** [comment]
@mattalexx I think this is a pretty good idea and I've been playing around with it with good results. However, there's one glaring problem that I think is unsolvable: we cannot show previews of audiobooks split by chapter. Libation doesn't store any chapter info. chapters are only retrieved from Audible on-demand when liberating a book. We could make something up (like we already do in the template editor), but then it's no longer a truly evaluated file path. Or we could ignore multipart filenames and only show single-part paths, but I'm not sure how useful that would be.

Alternatively, instead of adding a column to the main grid we could modify the template editor to allow users to choose a book to use for previewing templates.

**Comment by mattalexx** [comment]
> Alternatively, instead of adding a column to the main grid we could modify the template editor to allow users to choose a book to use for previewing templates.

That's even better.

**Comment by CLHatch** [comment]
> > Alternatively, instead of adding a column to the main grid we could modify the template editor to allow users to choose a book to use for previewing templates.
> 
> That's even better. That's when I'd need the information the most.

I like that idea, although there is the issue of "what if I don't have a book to view".  Say, a new account, or if it's a podcast, no podcasts in the account yet.

**Comment by rmcrackan** [comment]
> there is the issue of "what if I don't have a book to view". Say, a new account, or if it's a podcast, no podcasts in the account yet.

If you don't have any books in your audible account and can't be bothered to add a free podcast, I'm not sure what good Libation is going to do for you anyway 😄

**Comment by Mbucari** [comment]
New template editor context menu has been added in version [v11.0.0](https://github.com/rmcrackan/Libation/releases/tag/v11.0.0)
