### ISSUE TITLE
separate MP3 file per chapter does not seem to work

### ISSUE THREAD

**Issue by pellcorp** [rmcrackan/Libation#724]
**Describe the bug**
Is the new feature to have a single MP3 with embedded cue mean that old feature to have separate files no longer works?

**To Reproduce**
Convert to MP3 after enabling separate file per chapter, only one MP3 produced.
I don't have a player that can verify if the file has an embedded cue so don't don't if it's even doing that correctly 

**Expected behavior**
Produce separate MP3 files 

**Screenshots**

**Platform**

[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]
Fedora

**Log Files**
Attach your Libation log file here.

**Comment by Mbucari** [comment]
There are 2 ways for ibation to create MP#s

1. Download and decrypt directly to mp3. This only happens if you select "Download my books as .MP3 files" option.
![image](https://github.com/rmcrackan/Libation/assets/37587114/29005276-883f-43f5-a0ff-df73d1f96688)
2. Convert already-downloaded M4B audiobooks to MP3. This is merely a conversion, so whatever audio file options you used to download the M4B will also apply to the converted MP3.

It sounds like you're using method 2. If you first downloaded the audiobook as a single-file M4B, you cannot convert that file into split MP3s. The splitting can only happen while downloading, so you'll need to re-download that audiobook as an mp3.

**Comment by fusentasticus** [comment]
@Mbucari I used method 2 after downloading in the default mode (and all settings in the default mode). Then, I right-clicked on "Convert to mp3" for a specific title. Nothing happened. I think that's an error. (Windows 10, 11.3.6.1). Also, if the conversion cannot be performed, then please have Libation report the problem as a user alert. Thanks!
-------
By the way: I solved the conversion problem by using "Convert all Mp4b to Mp3 ..." in the Liberate menu.
