### ISSUE TITLE
Libation lo longer opens in windows

### ISSUE THREAD

**Issue by Africats2** [rmcrackan/Libation#743]
**Describe the bug** It will not open, even when run as administrator
A clear and concise description of what the bug is. I had the app running yesterday, today it just won't open

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform** Win 11

[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.

**Comment by rmcrackan** [comment]
Sorry this is happening. I'm afraid there isn't enough information above to diagnose. Are you getting any popups? Are log files generated? Is it classic or chardonnay?

**Comment by autryld** [comment]
> Today I finally uninstalled and reinstalled and still it doesn't open. I would really love to cancel my audible and support you instead but,,,,

The program comes in a Zip package and it can be installed wherever you put it. It's not recommended to put it in \Program Files\Libation.  This time I put mine in \Users\username\Program Files\Libation\".  Anyway, I have been having a similar problem getting Libation to run on Windows 11. I don't recall the steps I took on my Windows 10 system but I didn't have the same issue. It just ran. 
For Windows 11,  I just did these steps this morning.  I ran the Windows Troubleshooter and selected apps and entered the full path for Libation.exe. I didn't take notes so you'll need to follow your instincts when following the menus. You'll need to provide the program path to the troubleshooter. When it asked for the version of Windows, I selected "I don't know" because Windows 10 and 11 were not listed. 
By the way, I have no idea what the troubleshoot tool did but I appreciate the fact that Libation ran when I finished. 
If this is your first experience with Libation, you will find the Audible login a bit weird to say the least. Also, you may want to take the Libation guided tour. 
When you know it works, you can create a shortcut for it on the taskbar.

**Comment by Africats2** [comment]
I created a folder on the desktop to extract the files in. I have the classic. Like I said, it was working just fine. I had downloaded about a dozen books maybe? Woke up the next morning and tried to open libation and it just wouldn't open. No error, nothing happens period. It's never worked since. I've now ended up paying for another month waiting to get this sorted because I can't get my books downloaded 🙃

**Comment by autryld** [comment]
> I created a folder on the desktop to extract the files in. I have the classic. Like I said, it was working just fine. I had downloaded about a dozen books maybe? Woke up the next morning and tried to open libation and it just wouldn't open. No error, nothing happens period. It's never worked since. I've now ended up paying for another month waiting to get this sorted because I can't get my books downloaded 🙃

It's not clear if you are referring to audiobooks you purchased or ones that were available at no cost.  If you cancel your Audible subscription, you get to keep audiobooks you paid for with a credit or a credit card. If, on the other hand you are referring to "free" books I can understand your concern.  I noticed that a few of the "free" titles I added to my library were no longer "free" and because I missed the opportunity to liberate them, I can no longer download them.  Strangely, they remain in my library but are neither playable or downloadable. 

Check this webpage out: 
https://help.audible.com.au/s/article/will-my-audiobooks-disappear-after-i-cancel
"Will my audiobooks disappear after I cancel?
The titles that you purchase from Audible with a credit or credit card are yours to keep and are available to be downloaded across multiple devices. Although you can remove your audiobook(s) from a specific device, they remain in your online Library.

Even if you opt to cancel your Audible membership, your account remains active. This means that your purchased titles will always be accessible on any device that you use for listening."

**Comment by Africats2** [comment]
I haven't canceled my subscription yet, and I have many purchased books on there. But either way libation simply won't open. It was working fine. I have no further information to provide because I'm not getting any error or anything. I double click and absolutely nothing happens. I try running as administrator. I tried right clicking and choosing open. I tried completely uninstalling and reinstall. I don't understand why one day it was running fine for several days, then the next day it simply won't open

**Comment by thevoltagesource** [comment]
I had a similar experience last week on my Mac.  Libation opened just fine the last time I used it, but this time it would crash and only show the app window for a brief moment, if at all.  I downloaded the latest version and ran it from an alternate path, but I still had the same results. I went looking for any clues and found that Libation left a ```LibationCrash.log``` file in my user home directory.  The log file reported a JSON error in a config.  After checking all the config files I found and extra ```}``` at the end of the ```AccountsSettings.json```.  Removed the extra character, saved the file, and it was back to working. Not sure why this happened, but i hope this helps.

**Comment by rmcrackan** [comment]
I can't begin to imagine why there's an extra `}` but that explains a lot. There's been several bug reports lately about issues with this file. Since this is the only file that contains truly sensitive information, I couldn't request it from users for examination; the best I could do was recommend that they delete it try again.

Thank you so much for sharing your findings!

**Comment by CLHatch** [comment]
> I can't begin to imagine why there's an extra `}` but that explains a lot. There's been several bug reports lately about issues with this file. Since this is the only file that contains truly sensitive information, I couldn't request it from users for examination; the best I could do was recommend that they delete it try again.
> 
> Thank you so much for sharing your findings!

Is there any possibility that when Libation saves out that file it is somehow over-writing the existing text instead of writing a new copy out?  And if the the "new" file is shorter, it then keeps the end of the "old" file there?

**Comment by Africats2** [comment]
I will install again today and try to figure this out. Thanks for the
information

Lynnae Krenkel

**Comment by Africats2** [comment]
Description: A .NET application failed.
Application: Libation.exe
Path: C:\Users\afric\OneDrive\Desktop\Libation.exe
Message: The application to execute does not exist:
'C:\Users\afric\OneDrive\Desktop\Libation.dll'.
This is the error I get, but I have it reinstalled

**Comment by rmcrackan** [comment]
> C:\Users\afric\OneDrive\Desktop\Libation.exe

The exe must remain in the same directory as all the other files from the zip. You're welcome to create a shortcut on the desktop though.

**Comment by Africats2** [comment]
I had just figured that out and was writing to tell you my mistake when I
saw you had responded 🙈 I feel so dumb. thank you, I am sorry

**Comment by rmcrackan** [comment]
No worries. Happens to the best of us.
