### ISSUE TITLE
Why is mono downsampling recommended?

### ISSUE THREAD

**Issue by RokeJulianLockhart** [rmcrackan/Libation#764]
We should be using GitHub Discussions for questions like this, but I don't know where to ask.

![Screenshot_20230925_223655](https://github.com/rmcrackan/Libation/assets/42837531/600b5342-b844-4dde-9afa-b00c9fc2320f)

**Comment by CLHatch** [comment]
> We should be using GitHub Discussions for questions like this, but I don't know where to ask.
> 
> ![Screenshot_20230925_223655](https://user-images.githubusercontent.com/42837531/270479131-600b5342-b844-4dde-9afa-b00c9fc2320f.png)

Likely because most "stereo" audiobooks actually just duplicate the same audio for both channels.  Which means that you can halve the storage used by changing it to a single channel.

That said, that is only for `mp3` files.  I personally prefer to have it keep the original audio, in an `m4b` file.  When doing that, all the `mp3` options on the right are ignored anyways.
![image](https://github.com/rmcrackan/Libation/assets/13066223/be5d95af-8229-480f-9427-14204a9a2d87)

**Comment by Mbucari** [comment]
@RokeJulianLockhart everything @CLHatch is correct. Additionally, mono encoding is significantly faster than stereo encoding.
