### ISSUE TITLE
error occurred while trying to process book

### ISSUE THREAD

**Issue by nrbeaton** [rmcrackan/Libation#767]
**Describe the bug**
I'm trying to import a new book -- the download gets to 100% and then it fails.

**Platform**
Fedora 38 (KDE Plasma under Wayland)

**Log Files**
Attached.
[_Log202309.log](https://github.com/rmcrackan/Libation/files/12737765/_Log202309.log)

**Comment by Mbucari** [comment]
@nrbeaton Correct me if I'm wrong, but I'm almost certain that this is the same issue as #717

The problem is that books are first downloaded to your temp folder on your linux system drive which is formatted btrfs or ext4, but upon completion they're being moved to an external hard drive (NEWMEDIA) which is formatted NTFS or (ex)FAT. Some books have a colon (`:`) in the title, which is a legal filename character on btrfs or ext4 but illegal on NTFS and (ex)FAT. Your choices are:

1. Use the built-in character replacement tool to replace [illegal filename characters](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions).
2. Reformat your external hard drive to btrfs or ext4.
3. Store your books somewhere else.

**Comment by nrbeaton** [comment]
@Mbucari ah yes changing the colon to another character fixed it. Thank you!
