### ISSUE TITLE
OSX 14.1.1, download or conversion to MP3 not possible

### ISSUE THREAD

**Issue by martymccasland** [rmcrackan/Libation#798]
**Describe the bug**
Liberate to MP3 fails for all books.

**To Reproduce**
1. Download any Audible book
2. Attempt to convert it

**Expected behavior**
Conversion to MP3.

**Platform**
OSX 14.1.1

**Comment by Wizard-Sauna** [comment]
I think I may have found the issue. I force quit the application. Then installed the Libation.11.2.0-macOSchardonnay-arm64.tgz in addition to the -x64.tgz. I then went to Finder and opened the file so that I could bypass the OS not recognizing error. I ran it from there and it seems to be working fine. I was able to play it through the Apple music app as an MP3. YAY!

**Comment by rmcrackan** [comment]
If @Wizard-Sauna 's idea doesn't work, could you attach a log file to this ticket? You can find it by going into settings and clicking the 'open log folder' button.

**Comment by rmcrackan** [comment]
Would you mind trying the new v11.3 and see if it works for you?

**Comment by martymccasland** [comment]
Thanks for reaching out.   I found a good workflow using OpenAudible and AudioBookBuilder… Works flawlessly and I deleted your program.  Regardless, I will try your program again in the future if this workflow stops working.  I also thank you for reaching out.
-mm


From: rmcrackan ***@***.***>
Date: Wednesday, January 3, 2024 at 11:30 AM
To: rmcrackan/Libation ***@***.***>
Cc: martymccasland ***@***.***>, Author ***@***.***>
Subject: Re: [rmcrackan/Libation] OSX 14.1.1, download or conversion to MP3 not possible (Issue #798)

Would you mind trying the new v11.3 and see if it works for you?
