### ISSUE TITLE
Could not deserialise json

### ISSUE THREAD

**Issue by rustygorgon** [rmcrackan/Libation#804]
**Describe the bug**
Unexpected error. When I open libation it immediately moves to this error message.

**To Reproduce**
I installed Libation for the first time yesterday, using the Classic-Libation.11.2.0-windows-classic files. It worked for downloading and backing up about 80 books of 150. Today, when I opened my laptop, it wanted me to re-sign in to my amazon account, even though I had checked 'keep me signed in'. (related or unrelated, my Outlook accounts had also signed out). I decided to sign in again after I restarted my computer today.

Outlook appears to have updated but no windows updates have occurred other than a security intelligence update for Microsoft Defender, I don't know if that might have done something.

Now, opening Libation brings up this message. Closing the message will open Libation without my library. Trying to rescan my library or open the accounts settings also brings up this message again.

I'm working on Windows 10 Home edition.

**Log Files**
Log before this issue started:
[_Log202312_002.zip](https://github.com/rmcrackan/Libation/files/13538458/_Log202312_002.zip)

Most recent log:
[_Log202312_003.zip](https://github.com/rmcrackan/Libation/files/13538457/_Log202312_003.zip)

Thanks for making such a useful program, if there is any other information you need please let me know.

**Comment by rmcrackan** [comment]
I'm getting suspicious of v11.2. I think something went wrong. I deleted it from my downloads page. Try v11.1 and see if it fixes your issue -- https://github.com/rmcrackan/Libation/releases/tag/v11.1.0 . If you need help hooking 11.1 up to your library files, I'm happy to help.

I'm going to close this ticket since I think it's really a 11.2 bug, which no longer exists. You can still reply here though and I'll get your notification.
