### ISSUE TITLE
error importing library 

### ISSUE THREAD

**Issue by simmy87** [rmcrackan/Libation#826]
[_Log202401_004.zip](https://github.com/rmcrackan/Libation/files/13933476/_Log202401_004.zip)

**Comment by rmcrackan** [comment]
Thanks for the log file. It looks like you filled up your drive.

**Comment by BlaBlubBlub** [comment]
I too get an error every time I try to scan my library.

Log: 
[_Log202401_001.zip](https://github.com/rmcrackan/Libation/files/13954594/_Log202401_001.zip)

**Comment by rmcrackan** [comment]
Could you try this new prerelease? It has better error reporting around that area. Hopefully the next log can shed some light -- https://github.com/rmcrackan/Libation/releases/tag/v11.3.3

**Comment by Jonas-Johnson** [comment]
[_Log202401.zip](https://github.com/rmcrackan/Libation/files/13991626/_Log202401.zip)

**Comment by BlaBlubBlub** [comment]
A fresh log straight from v11.3.3

[_Log202401_002.zip](https://github.com/rmcrackan/Libation/files/13998976/_Log202401_002.zip)

**Comment by extuary** [comment]
I'm having this issue as well. (I opened Bug Report #824 about this, then it seemed to sorta resolve for a day when I switched to 11.3? Now it's back and I can't scan my library at all.)

I've now encountered this issue using (originally) 11.2, and now 11.1 and 11.3. 
I've also tried deleting the entire Libation folder (the `C:\Users\<my_account>\Libation` one) to do a fresh install, but that didn't seem to help.
Here's my log from today, getting the error using 11.3.4.
[_Log202401.zip](https://github.com/rmcrackan/Libation/files/14060961/_Log202401.zip)
and using 11.1
[_Log202401.zip](https://github.com/rmcrackan/Libation/files/14061045/_Log202401.zip)


You mentioned that an earlier log said `The request failed due to an underlying issue such as network connectivity, DNS failure, server certificate validation or timeout.` That language is still in these new logs. Though, I'm not having any noticeable network issues.

**Comment by samanthah** [comment]
Same issue on 11.3.4, first time using Libation so I'm glad to see I'm not the only one
[libationerror.txt](https://github.com/rmcrackan/Libation/files/14141202/libationerror.txt)

**Comment by BlaBlubBlub** [comment]
I recently have noticed a workaround for the Issue. establishing a WiFi Connection to my smartphone, while the smartphone is uesed as a Wifi Hotspot it is connected to my WiFi Modem.  so the Signal does not go directly to the Modem but tages a walk around the conor to my Phone. As i was digging deeper i realized that my phone does not use IPv6 only v4 and as i have deactivated IPv6 in my Networksettings it works fine.

dont Know if it is a general problem with IPv6 (and audible servers) or if it only is a problem on my Providers side. hopefully deactivating IPv6 would solve this issue for the others.

**Comment by rmcrackan** [comment]
@BlaBlubBlub You're the 2nd person to bring up the ipv6 issue. This makes absolutely no sense to me why it should be the case and I have no idea how to walk a lay person through this but I'm so glad that a common cause is becoming more clear. Thanks for your clever work-around.

**Comment by CLHatch** [comment]
> @BlaBlubBlub You're the 2nd person to bring up the ipv6 issue. This makes absolutely no sense to me why it should be the case and I have no idea how to walk a lay person through this but I'm so glad that a common cause is becoming more clear. Thanks for your clever work-around.

Just as an FYI, I have an IPv6 address on my Windows 11 PC, and I've had no issues here.  I'm currently using Chardonnay v11.3.5.1.
